### ISSUE TITLE
high level: Make sure context can be kept open

### ISSUE THREAD

**Issue by johnandersen777** [intel/dffml#1112]
https://github.com/intel/dffml/blob/5270c614ff1d494abd6e584f4a6d193a3f76991d/dffml/high_level.py#L402-L404

https://github.com/intel/dffml/blob/5270c614ff1d494abd6e584f4a6d193a3f76991d/dffml/high_level.py#L466-L468

https://github.com/intel/dffml/blob/5270c614ff1d494abd6e584f4a6d193a3f76991d/dffml/high_level.py#L536-L538

**Comment by pdxjohnny** [comment]
@programmer290399 If you're looking for issues this is a good one.

The problem here is that we are only testing [1] a case where `SLRModel` is used and it `isinstance(..., Model)` which doesn't trigger the undefined `mctx` variable bug in the above cases.

The goal is for the below code to work.

```python
import asyncio
from dffml import *
from dffml_model_scikit.scikit_models import LinearRegressionModel

model = LinearRegressionModel(
    features=Features(Feature("Years", int, 1),),
    predict=Feature("Salary", int, 1),
    location="tempdir",
)


async def main():
    # Load model and source using double context entry pattern
    # Here we create a memory backed source. Equivlant to what the above example
    # does behind the scenes when passing in dict objects.
    async with model, MemorySource(
        records=[
            Record(i, data={"features": {"Years": i}}) for i in range(6, 8)
        ]
    ) as source:
        async with model() as mctx, source() as sctx:
            # Train the model
            await train(
                mctx,
                {"Years": 0, "Salary": 10},
                {"Years": 1, "Salary": 20},
                {"Years": 2, "Salary": 30},
                {"Years": 3, "Salary": 40},
            )
            # Make predictions
            async for i, features, prediction in predict(mctx, sctx):
                features["Salary"] = round(prediction["Salary"]["value"])
                print(features)


asyncio.run(main())
```

```console
(.venv) $ python model.py
Traceback (most recent call last):
  File "model.py", line 36, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "model.py", line 28, in main
    {"Years": 3, "Salary": 40},
  File "/home/johnsa1/Documents/python/dffml/dffml/high_level/ml.py", line 62, in train
    return await mctx.train(sctx)
UnboundLocalError: local variable 'mctx' referenced before assignment
```

References:
- [1]: https://intel.github.io/dffml/master/tutorials/doublecontextentry.html

**Comment by programmer290399** [comment]
I'm on it !! 👍🏽
