### ISSUE TITLE
docs: unable to build the docs.

### ISSUE THREAD

**Issue by sk-ip** [intel/dffml#1120]
## Describe the bug
Unable to build the documentation
## Steps To Reproduce
https://intel.github.io/dffml/master/contributing/docs.html
## Expected behavior
a directory pages should be generated.
## Logs or Screenshots

```log
ubuntu@ip-172-31-31-53:~/dffml$ dffml service dev docs
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/dffml", line 8, in <module>
    sys.exit(CLI.main())
  File "/home/ubuntu/.local/lib/python3.8/site-packages/dffml/util/cli/cmd.py", line 288, in main
    result = loop.run_until_complete(cls._main(*argv[1:]))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/dffml/util/cli/cmd.py", line 238, in _main
    result = await cls.cli(*args)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/dffml/util/cli/cmd.py", line 224, in cli
    return await cmd.do_run()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/dffml/util/cli/cmd.py", line 203, in do_run
    return await self.run()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/dffml/service/dev.py", line 1122, in run
    file_path.symlink_to(root.joinpath(*source))
  File "/usr/lib/python3.8/pathlib.py", line 1379, in symlink_to
    self._accessor.symlink(target, self, target_is_directory)
  File "/usr/lib/python3.8/pathlib.py", line 442, in symlink
    return os.symlink(a, b)
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/.local/lib/python3.8/site-packages/CHANGELOG.md' -> '/home/ubuntu/.local/lib/python3.8/site-packages/docs/changelog.md'
```

**Comment by pdxjohnny** [comment]
It looks like `dffml` was installed without the `-e` flag to `pip`

**Comment by pdxjohnny** [comment]
Let's try uninstalling dffml and reinstalling with `-e`

```console
$ pip uninstall -y dffml
$ pip install -e .[dev]
```

**Comment by sk-ip** [comment]
Installed dffml using `-e` flag, it is showing the following error. I also find that sphinx was installed, using `pip list`
```log
ubuntu@ip-172-31-31-53:~/dffml$ dffml service dev docs
$ /usr/bin/python3 /home/ubuntu/dffml/scripts/docs.py
$ /usr/bin/python3 /home/ubuntu/dffml/scripts/docs_api.py
$ sphinx-build -W -b html docs /home/ubuntu/dffml/pages
Running Sphinx v4.0.2
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 196 source files that are out of date
updating environment: [new config] 196 added, 0 changed, 0 removed
/home/ubuntu/.local/lib/python3.8/site-packages/recommonmark/parser.py:75: UserWarning: Container node skipped: type=document
  warn("Container node skipped: type={0}".format(mdnode.t))
/home/ubuntu/.local/lib/python3.8/site-packages/recommonmark/parser.py:75: UserWarning: Container node skipped: type=document
  warn("Container node skipped: type={0}".format(mdnode.t))
reading sources... [100%] tutorials/sources/index
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] tutorials/sources/index

Warning, treated as error:
/home/ubuntu/dffml/docs/examples/flower17/flower17_pytorch.rst:4:undefined label: plugin_model_dffml_model_pytorch_alexnet
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/dffml", line 33, in <module>
    sys.exit(load_entry_point('dffml', 'console_scripts', 'dffml')())
  File "/home/ubuntu/dffml/dffml/util/cli/cmd.py", line 288, in main
    result = loop.run_until_complete(cls._main(*argv[1:]))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/ubuntu/dffml/dffml/util/cli/cmd.py", line 238, in _main
    result = await cls.cli(*args)
  File "/home/ubuntu/dffml/dffml/util/cli/cmd.py", line 224, in cli
    return await cmd.do_run()
  File "/home/ubuntu/dffml/dffml/util/cli/cmd.py", line 203, in do_run
    return await self.run()
  File "/home/ubuntu/dffml/dffml/service/dev.py", line 1157, in run
    raise SphinxBuildError
dffml.service.dev.SphinxBuildError: [ERROR] Failed run sphinx, is it installed (pip install -U .[dev])?
```

**Comment by pdxjohnny** [comment]
```
/home/ubuntu/dffml/docs/examples/flower17/flower17_pytorch.rst:4:undefined label: plugin_model_dffml_model_pytorch_alexnet
```

Looks like you don't have the other plugins installed. Ideally you wouldn't need them.. However, that the way its currently setup is the docs need all the plugins installed to be built.

Ideally we can get around this when we implement 2ndparty plugins.

**Comment by pdxjohnny** [comment]
Labeling with 2ndparty to make sure we take a look at this for the implementation of that

**Comment by programmer290399** [comment]
* I had this same issue of building docs in dev mode , looks like recent changes and additions to the documentation has caused this , you can check my error below : 
```bash
dffml on  master [?] via 🐍 v3.7.10 (.venv) took 5s 
❯ dffml service dev docs
$ /home/saahil/rps/dffml/.venv/bin/python3.7 /home/saahil/rps/dffml/scripts/docs.py
Follow the instructions mentioned at https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Python#installing to install necessary dependencies for vowpal wabbit.
dispatcher.py:151: FutureWarning: 
Scikit-learn patching with daal4py is deprecated and will be removed in the future.
Use Intel(R) Extension for Scikit-learn* module instead (pip install scikit-learn-intelex).
To enable patching, please use one of the following options:
1) From the command line:
    python -m sklearnex <your_script>
2) From your script:
    from sklearnex import patch_sklearn
    patch_sklearn()
Intel(R) oneAPI Data Analytics Library solvers for sklearn enabled: https://intelpython.github.io/daal4py/sklearn.html
$ /home/saahil/rps/dffml/.venv/bin/python3.7 /home/saahil/rps/dffml/scripts/docs_api.py
$ sphinx-build -W -b html docs /home/saahil/rps/dffml/pages
Running Sphinx v4.0.2
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 194 source files that are out of date
updating environment: [new config] 194 added, 0 changed, 0 removed
/home/saahil/rps/dffml/.venv/lib/python3.7/site-packages/recommonmark/parser.py:75: UserWarning: Container node skipped: type=document
  warn("Container node skipped: type={0}".format(mdnode.t))
reading sources... [ 77%] examples/notebooks/moving_between_models                                                        
Notebook error:
PandocMissing in examples/notebooks/moving_between_models.nblink:
Pandoc wasn't found.
Please check that pandoc is installed:
https://pandoc.org/installing.html
Traceback (most recent call last):
  File "/home/saahil/rps/dffml/.venv/bin/dffml", line 33, in <module>
    sys.exit(load_entry_point('dffml', 'console_scripts', 'dffml')())
  File "/home/saahil/rps/dffml/dffml/util/cli/cmd.py", line 288, in main
    result = loop.run_until_complete(cls._main(*argv[1:]))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/home/saahil/rps/dffml/dffml/util/cli/cmd.py", line 238, in _main
    result = await cls.cli(*args)
  File "/home/saahil/rps/dffml/dffml/util/cli/cmd.py", line 224, in cli
    return await cmd.do_run()
  File "/home/saahil/rps/dffml/dffml/util/cli/cmd.py", line 203, in do_run
    return await self.run()
  File "/home/saahil/rps/dffml/dffml/service/dev.py", line 1157, in run
    raise SphinxBuildError
dffml.service.dev.SphinxBuildError: [ERROR] Failed run sphinx, is it installed (pip install -U .[dev])?
```

* According to this ⬆️ , pandoc is not installed but it is installed in the env : 
```
dffml on  master [?] via 🐍 v3.7.10 (.venv) took 39s 
❯ pip show pandoc
Name: pandoc
Version: 1.0.2
Summary: Pandoc Documents for Python
Home-page: https://github.com/boisgera/pandoc
Author: Sébastien Boisgérault
Author-email: Sebastien.Boisgerault@mines-paristech.fr
License: MIT License
Location: /home/saahil/rps/dffml/.venv/lib/python3.7/site-packages
Requires: ply
Required-by: 
```
