### ISSUE TITLE
df: types: NamedTuple._field_types removed in 3.9

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#1125]
```
Traceback (most recent call last):
  File "/home/johnsa1/.local/bin/dffml", line 33, in <module>
    sys.exit(load_entry_point('dffml', 'console_scripts', 'dffml')())
  File "/home/johnsa1/Documents/python/dffml/dffml/util/cli/cmd.py", line 288, in main
    result = loop.run_until_complete(cls._main(*argv[1:]))
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/johnsa1/Documents/python/dffml/dffml/util/cli/cmd.py", line 238, in _main
    result = await cls.cli(*args)
  File "/home/johnsa1/Documents/python/dffml/dffml/util/cli/cmd.py", line 224, in cli
    return await cmd.do_run()
  File "/home/johnsa1/Documents/python/dffml/dffml/util/cli/cmd.py", line 203, in do_run
    return await self.run()
  File "/home/johnsa1/Documents/python/dffml/dffml/cli/dataflow.py", line 115, in run
    dataflow = DataFlow(
  File "/home/johnsa1/Documents/python/dffml/dffml/df/types.py", line 569, in __init__
    self.update(auto_flow=bool(self.flow is None))
  File "/home/johnsa1/Documents/python/dffml/dffml/df/types.py", line 575, in update
    self.flow = self.auto_flow()
  File "/home/johnsa1/Documents/python/dffml/dffml/df/types.py", line 801, in auto_flow
    if output_definition == definition:
  File "/home/johnsa1/Documents/python/dffml/dffml/df/types.py", line 89, in __eq__
    return bool(self.export() == other.export())
  File "/home/johnsa1/Documents/python/dffml/dffml/df/types.py", line 105, in export
    types=self.spec._field_types,
AttributeError: type object 'GitRepoSpec' has no attribute '_field_types'
```

**Comment by pdxjohnny** [comment]
Great... still hitting this bug...
