### ISSUE TITLE
setup.py: test: Local tests failing to run altogether 

### ISSUE THREAD

**Issue by programmer290399** [intel/dffml#1169]
## Describe the bug

Trying to run all local tests results in error.

## Steps To Reproduce
Just ran the following command,

```bash
$ python setup.py test
```

## Expected behavior

All the tests should run resulting in a list of failed or passed tets

## Logs or Screenshots

```log
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
running egg_info
writing dffml.egg-info/PKG-INFO
writing dependency_links to dffml.egg-info/dependency_links.txt
writing entry points to dffml.egg-info/entry_points.txt
writing requirements to dffml.egg-info/requires.txt
writing top-level names to dffml.egg-info/top_level.txt
reading manifest file 'dffml.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'LICENSE'
writing manifest file 'dffml.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 166, in <module>
    "clf = dffml.accuracy.clf:ClassificationAccuracy",
  File "/home/saahil/rps/dffml/.venv/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/saahil/rps/dffml/.venv/lib/python3.7/site-packages/setuptools/command/test.py", line 232, in run
    self.run_tests()
  File "/home/saahil/rps/dffml/.venv/lib/python3.7/site-packages/setuptools/command/test.py", line 254, in run_tests
    exit=False,
  File "/usr/lib/python3.7/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python3.7/unittest/main.py", line 124, in parseArgs
    self._do_discovery(argv[2:])
  File "/usr/lib/python3.7/unittest/main.py", line 244, in _do_discovery
    self.createTests(from_discovery=True, Loader=Loader)
  File "/usr/lib/python3.7/unittest/main.py", line 154, in createTests
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/usr/lib/python3.7/unittest/loader.py", line 349, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/usr/lib/python3.7/unittest/loader.py", line 406, in _find_tests
    full_path, pattern, namespace)
  File "/usr/lib/python3.7/unittest/loader.py", line 483, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/home/saahil/rps/dffml/.venv/lib/python3.7/site-packages/setuptools/command/test.py", line 50, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib/python3.7/unittest/loader.py", line 205, in loadTestsFromName
    test = obj()
TypeError: accuracy() missing 2 required positional arguments: 'model' and 'accuracy_scorer'
```

## Packages in use and versions
```
dffml 0.4.0 
dffml-config-yaml 0.1.0 
dffml-config-image 0.1.0 
dffml-model-scratch 0.1.0 
dffml-model-scikit 0.1.0 
dffml-model-tensorflow 0.3.0 
dffml-model-tensorflow-hub 0.1.0 
dffml-model-vowpalWabbit 0.1.0 
dffml-model-xgboost 0.1.0 
dffml-model-pytorch 0.1.0 
dffml-model-spacy 0.1.0 
dffml-model-daal4py 0.1.0 
dffml-model-autosklearn 0.1.0 
dffml-feature-git 0.3.0 
dffml-feature-auth 0.1.0 
dffml-operations-binsec 0.1.0 
dffml-operations-deploy 0.1.0 
dffml-operations-image 0.1.0 
dffml-operations-nlp 0.1.0 
dffml-service-http 0.1.0 
dffml-source-mysql 0.1.0 
```

## Misc Notes

Looks like a minor issue which was caused by recent merge of Accuracy scorers , maybe @sk-ip  can help.

**Comment by sk-ip** [comment]
So with the recent merge that happened, for testing we have started using

```console
$ python3 -m unittest discover -v
```
ref: https://intel.github.io/dffml/master/contributing/testing.html#testing
