### ISSUE TITLE
ci: run: consoletest: Hang on exit creates timeout failure

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#1203]
Had a similar issue with commit linting where a git command failed from a
subprocess run, causing the CI the hang until the job as canceled.

https://github.com/intel/dffml/runs/3395514117

```
2021-08-20T16:25:06.3462470Z Traceback (most recent call last):
2021-08-20T16:25:06.3463972Z   File "/home/runner/work/dffml/dffml/dffml/util/testing/consoletest/builder.py", line 129, in test_doc
2021-08-20T16:25:06.3464772Z     setup=self.consoletest_test_setup,
2021-08-20T16:25:06.3465622Z   File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
2021-08-20T16:25:06.3466468Z     return future.result()
2021-08-20T16:25:06.3467184Z   File "/home/runner/work/dffml/dffml/dffml/util/testing/consoletest/runner.py", line 105, in run_nodes
2021-08-20T16:25:06.3467847Z     await command.run(ctx)
2021-08-20T16:25:06.3468531Z   File "/home/runner/work/dffml/dffml/dffml/util/testing/consoletest/commands.py", line 412, in run
2021-08-20T16:25:06.3469195Z     daemon=bool(self.daemon),
2021-08-20T16:25:06.3469933Z   File "/home/runner/work/dffml/dffml/dffml/util/testing/consoletest/commands.py", line 336, in run_commands
2021-08-20T16:25:06.3470695Z     raise RuntimeError("\n".join(errors))
2021-08-20T16:25:06.3472181Z RuntimeError: Failed to run: ['dffml', 'list', 'records', '-sources', 'portal=sources.sap_portal_repos_json:SAPPortalReposJSONSource', '-source-portal-filename', 'html-client/repos.json']
2021-08-20T16:25:06.3473155Z 
2021-08-20T16:25:06.3473480Z No more tempdir
2021-08-20T16:25:06.3473728Z 
2021-08-20T16:25:06.3473920Z 
2021-08-20T16:25:06.3474255Z consoletest summary
2021-08-20T16:25:06.3474615Z ===================
2021-08-20T16:25:06.3474922Z     1 test
2021-08-20T16:25:06.3475258Z     1 failure in tests
2021-08-20T16:25:06.3475906Z [01mbuild finished with problems, 19 warnings.[39;49;00m
2021-08-20T16:25:06.3476363Z FAIL
2021-08-20T16:25:06.3476562Z 
2021-08-20T16:25:06.3476884Z ======================================================================
2021-08-20T16:25:06.3477521Z FAIL: test_examples_swportal (tests.docs.test_consoletest.TestDocs)
2021-08-20T16:25:06.3478416Z ----------------------------------------------------------------------
2021-08-20T16:25:06.3479083Z Traceback (most recent call last):
2021-08-20T16:25:06.3479834Z   File "/home/runner/work/dffml/dffml/tests/docs/test_consoletest.py", line 150, in builder_testcase
2021-08-20T16:25:06.3480589Z     self.assertFalse(app.statuscode)
2021-08-20T16:25:06.3481135Z AssertionError: 1 is not false
2021-08-20T16:25:06.3481499Z 
2021-08-20T16:25:06.3482104Z ----------------------------------------------------------------------
2021-08-20T16:25:06.3482571Z Ran 1 test in 16.299s
2021-08-20T16:25:06.3482807Z 
2021-08-20T16:25:06.3483136Z FAILED (failures=1)
2021-08-20T22:21:55.7311955Z ##[error]The operation was canceled.
```

**Comment by programmer290399** [comment]
Ran this test locally with : 
` $ TEST_DOCS=1 python3 -m unittest -v tests.docs.test_consoletest.TestDocs.test_examples_swportal`
and it fails almost immediately in less than 20s , I wonder why its stuck for so many hours  in the CI 🤔
