### ISSUE TITLE
AttributeError: __aexit__ on CLI usage

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#136]
```log
root@c0f9c6704ae2:/usr/src/dffml#  dffml train -model scratchslr -features def:Years:int:1 -model-predict Salary -sources f=csv -source-filename dataset.csv -source-readonl
y -log debug
DEBUG:dffml.cli.Train:Setting features = [Years(DefFeature.<locals>.DefinedFeature)[<class 'int'>, 1]]
DEBUG:dffml.cli.Train:Setting log = 20
DEBUG:dffml.cli.Train:Setting model = <class 'dffml_model_scratch.slr.SLR'>
DEBUG:dffml.cli.Train:Setting sources = [<class 'dffml.util.entrypoint.Entrypoint.load_labeled.<locals>.Loaded'>]
DEBUG:dffml.cli.Train:Setting timeout = 120
DEBUG:dffml.cli.Train:Setting features = [Years(DefFeature.<locals>.DefinedFeature)[<class 'int'>, 1]]
DEBUG:dffml.cli.Train:Setting log = 20
DEBUG:dffml.cli.Train:Setting model = <class 'dffml_model_scratch.slr.SLR'>
DEBUG:dffml.cli.Train:Setting sources = [Entrypoint.load_labeled.<locals>.Loaded(CSVSourceConfig(filename='dataset.csv', label='unlabeled', readonly=True, key=None))]
DEBUG:dffml.cli.Train:Setting timeout = 120
DEBUG:dffml.cli.Train:Setting features = [Years(DefFeature.<locals>.DefinedFeature)[<class 'int'>, 1]]
DEBUG:dffml.cli.Train:Setting log = 20
DEBUG:dffml.cli.Train:Setting model = <class 'dffml_model_scratch.slr.SLR'>
DEBUG:dffml.cli.Train:Setting sources = [Entrypoint.load_labeled.<locals>.Loaded(CSVSourceConfig(filename='dataset.csv', label='unlabeled', readonly=True, key=None))]
DEBUG:dffml.cli.Train:Setting timeout = 120
DEBUG:dffml.util.AsyncContextManagerList.Sources:Entering: Entrypoint.load_labeled.<locals>.Loaded(CSVSourceConfig(filename='dataset.csv', label='unlabeled', readonly=True,
 key=None))
DEBUG:dffml.Entrypoint.load_labeled.<locals>.Loaded:Entrypoint.load_labeled.<locals>.Loaded(CSVSourceConfig(filename='dataset.csv', label='unlabeled', readonly=True, key=No
ne)) loaded 5 records
Traceback (most recent call last):
  File "/usr/local/bin/dffml", line 10, in <module>
    sys.exit(CLI.main())
  File "/usr/local/lib/python3.7/site-packages/dffml/util/cli/cmd.py", line 169, in main
    result = loop.run_until_complete(cls.cli(*argv[1:]))
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/site-packages/dffml/util/cli/cmd.py", line 150, in cli
    return await cmd.run()
  File "/usr/local/lib/python3.7/site-packages/dffml/cli.py", line 406, in run
    async with self.sources as sources, self.features as features, self.model as model:
AttributeError: __aexit__
```

**Comment by yashlamba** [comment]
I think this is because of self.model as model if related to slr else one of these `async with self.sources as sources, self.features as features, self.model as model:` is not a context manager

**Comment by pdxjohnny** [comment]
Problem was my fault used old docker image
