### ISSUE TITLE
df: linker: Correctly export specs and stages

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#204]
```
{
    "definitions": {
        "group_by_output": {
            "primitive": "Dict[str, List[Any]]",
            "spec": null
        },
        "group_by_spec": {
            "primitive": "Dict[str, Any]",
            "spec": Traceback (most recent call last):
  File "/home/johnsa1/.local/bin/shouldi", line 11, in <module>
    load_entry_point('shouldi', 'console_scripts', 'shouldi')()
  File "/home/johnsa1/Documents/python/dffml/dffml/util/cli/cmd.py", line 184, in main
    cls=cls.JSONEncoder,
  File "/usr/lib/python3.7/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/usr/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/home/johnsa1/Documents/python/dffml/dffml/util/cli/cmd.py", line 41, in default
    return json.JSONEncoder.default(self, obj)
  File "/usr/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type type is not JSON serializable
```

**Comment by pdxjohnny** [comment]
Done in dfass
