### ISSUE TITLE
model: Move features from init of ModelContext to Model

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#231]
Right now, features are passed to the `__init__` method of `ModelContext` subclasses. Instead, lets make features a part of the config of a `dffml.model.model.Model` class.

**Comment by aghinsa** [comment]
few doubts  :
1. So after moving it to  config of model we'll be passing features like this ->
```
dffml train \
-model tfdnnr\
-model-features\ 
            def:Feature1:float:1 \    
            def:Feature2:float:1 \
```
is this the intented result?
2. Since there is a `super().__init__(parent, features)` in almost all the `ModelContexts` ,they need to be changed rit?

**Comment by pdxjohnny** [comment]
@aghinsa Great!

I'm going to preface this with if #228 gets done first, this would be a lot less work.

1. Yes that is what it will look like on the command line.
2. Yes, That will need to be changed.
3. The way it works right now is that features is set from the CLI command (which subclasses from the FeaturesCMD CLI command class):
https://github.com/intel/dffml/blob/50b37429822996d20604c524a3cfc3f802eb1065/dffml/util/cli/cmds.py#L83-L89
4. That `Arg(...)` will need to be moved into the `args()` classmethod of each model, for example:
https://github.com/intel/dffml/blob/50b37429822996d20604c524a3cfc3f802eb1065/model/tensorflow/dffml_model_tensorflow/dnnc.py#L426-L436
5. A `features` property of type `dffml.feature.feature.Features` needs to be added to the `...ModelConfig` class of each model, for example:
https://github.com/intel/dffml/blob/50b37429822996d20604c524a3cfc3f802eb1065/model/tensorflow/dffml_model_tensorflow/dnnc.py#L91-L98
6. Then it needs to be retrieved in the `config()` classmethod of each model, for example:
https://github.com/intel/dffml/blob/50b37429822996d20604c524a3cfc3f802eb1065/model/tensorflow/dffml_model_tensorflow/dnnc.py#L494-L502
7. Everywhere `self.features` is used in a `ModelContext` use `self.parent.config.features` (This is not always true, some models change `self.features` to the subset of applicable features).

If  #228 gets done first, this task pretty much becomes 2, 5, & 7

**Comment by aghinsa** [comment]
Ohkay.I'll start with scikit models and for tf models i'll wait till you have merged tfdnnr,sounds okay?

**Comment by pdxjohnny** [comment]
In addition to `model.ModelConfig`, you'll need to add `features` to

### model/scikit 1

https://github.com/intel/dffml/blob/50b37429822996d20604c524a3cfc3f802eb1065/model/scikit/dffml_model_scikit/scikit_models.py#L106

### model/scikit 2

https://github.com/intel/dffml/blob/50b37429822996d20604c524a3cfc3f802eb1065/model/scikit/dffml_model_scikit/scikit_models.py#L117-L138


### model/scikit 3

https://github.com/intel/dffml/blob/50b37429822996d20604c524a3cfc3f802eb1065/model/scikit/dffml_model_scikit/scikit_models.py#L156-L160

### model/scratch 1

https://github.com/intel/dffml/blob/50b37429822996d20604c524a3cfc3f802eb1065/model/scratch/dffml_model_scratch/slr.py#L23-L25

### model/scratch 2

https://github.com/intel/dffml/blob/50b37429822996d20604c524a3cfc3f802eb1065/model/scratch/dffml_model_scratch/slr.py#L216-L242

### model/tensorflow 1

https://github.com/intel/dffml/blob/50b37429822996d20604c524a3cfc3f802eb1065/model/tensorflow/dffml_model_tensorflow/dnnc.py#L90-L101

### model/tensorflow 2

https://github.com/intel/dffml/blob/50b37429822996d20604c524a3cfc3f802eb1065/model/tensorflow/dffml_model_tensorflow/dnnc.py#L424-L502

**Comment by aghinsa** [comment]
Oh!My bad,i had missed the first one .

**Comment by aghinsa** [comment]
@pdxjohnny i made the changes for `scikit`,`tensorflow`,`scratch` and corresponding test_cases and all of them passed.But `test_cli` is failing and i'm not sure what all to change.
`python3.7 setup.py test -s tests/test_cli.py`.
```
running test
running egg_info
writing dffml.egg-info/PKG-INFO
writing dependency_links to dffml.egg-info/dependency_links.txt
writing entry points to dffml.egg-info/entry_points.txt
writing requirements to dffml.egg-info/requires.txt
writing top-level names to dffml.egg-info/top_level.txt
reading manifest file 'dffml.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'dffml.egg-info/SOURCES.txt'
running build_ext
test_run (tests.test_cli.TestAccuracy) ... /home/aghinsa/Documents/workspace/prep/global/dffml/dffml/source/json.py:79: DeprecationWarning: dict method will be removed in favor of export
  repo.src_url: repo.dict() for repo in self.mem.values()
ERROR
test_run (tests.test_cli.TestEvaluateAll) ... ERROR
test_run (tests.test_cli.TestEvaluateRepo) ... ERROR
test_run (tests.test_cli.TestListRepos) ... ok
test_csv_label (tests.test_cli.TestMerge) ... /home/aghinsa/Documents/workspace/prep/global/dffml/dffml/source/csv.py:217: DeprecationWarning: dict method will be removed in favor of export
  repo_data = repo.dict()
ok
test_json_label (tests.test_cli.TestMerge) ... ok
test_json_to_csv (tests.test_cli.TestMerge) ... ok
test_run (tests.test_cli.TestOperationsAll) ... ok
test_run (tests.test_cli.TestOperationsRepo) ... ok
test_run (tests.test_cli.TestPredictAll) ... ERROR
test_run (tests.test_cli.TestPredictRepo) ... ERROR
test_run (tests.test_cli.TestTrain) ... ERROR

======================================================================
ERROR: test_run (tests.test_cli.TestAccuracy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aghinsa/Documents/workspace/prep/global/dffml/dffml/util/asynctestcase.py", line 46, in run_it
    result = self.loop.run_until_complete(coro(*args, **kwargs))
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/home/aghinsa/Documents/workspace/prep/global/dffml/tests/test_cli.py", line 420, in test_run
    Accuracy.arg_features.modify(type=feature_load),
AttributeError: type object 'Accuracy' has no attribute 'arg_features'

======================================================================
ERROR: test_run (tests.test_cli.TestEvaluateAll)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aghinsa/Documents/workspace/prep/global/dffml/dffml/util/asynctestcase.py", line 46, in run_it
    result = self.loop.run_until_complete(coro(*args, **kwargs))
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/home/aghinsa/Documents/workspace/prep/global/dffml/tests/test_cli.py", line 358, in test_run
    "fake",
  File "/home/aghinsa/Documents/workspace/prep/global/dffml/dffml/util/cli/cmd.py", line 151, in cli
    return [res async for res in cmd.run()]
  File "/home/aghinsa/Documents/workspace/prep/global/dffml/dffml/util/cli/cmd.py", line 151, in <listcomp>
    return [res async for res in cmd.run()]
  File "/home/aghinsa/Documents/workspace/prep/global/dffml/dffml/cli.py", line 366, in run
    async with self.sources as sources, self.features as features:
AttributeError: 'EvaluateAll' object has no attribute 'features'

======================================================================
ERROR: test_run (tests.test_cli.TestEvaluateRepo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aghinsa/Documents/workspace/prep/global/dffml/dffml/util/asynctestcase.py", line 46, in run_it
    result = self.loop.run_until_complete(coro(*args, **kwargs))
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/home/aghinsa/Documents/workspace/prep/global/dffml/tests/test_cli.py", line 382, in test_run
    *subset_urls,
  File "/home/aghinsa/Documents/workspace/prep/global/dffml/dffml/util/cli/cmd.py", line 151, in cli
    return [res async for res in cmd.run()]
  File "/home/aghinsa/Documents/workspace/prep/global/dffml/dffml/util/cli/cmd.py", line 151, in <listcomp>
    return [res async for res in cmd.run()]
  File "/home/aghinsa/Documents/workspace/prep/global/dffml/dffml/cli.py", line 366, in run
    async with self.sources as sources, self.features as features:
AttributeError: 'EvaluateRepo' object has no attribute 'features'

======================================================================
ERROR: test_run (tests.test_cli.TestPredictAll)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aghinsa/Documents/workspace/prep/global/dffml/dffml/util/asynctestcase.py", line 46, in run_it
    result = self.loop.run_until_complete(coro(*args, **kwargs))
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/home/aghinsa/Documents/workspace/prep/global/dffml/tests/test_cli.py", line 444, in test_run
    PredictAll.arg_features.modify(type=feature_load),
AttributeError: type object 'PredictAll' has no attribute 'arg_features'

======================================================================
ERROR: test_run (tests.test_cli.TestPredictRepo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aghinsa/Documents/workspace/prep/global/dffml/dffml/util/asynctestcase.py", line 46, in run_it
    result = self.loop.run_until_complete(coro(*args, **kwargs))
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/home/aghinsa/Documents/workspace/prep/global/dffml/tests/test_cli.py", line 473, in test_run
    PredictRepo.arg_features.modify(type=feature_load),
AttributeError: type object 'PredictRepo' has no attribute 'arg_features'

======================================================================
ERROR: test_run (tests.test_cli.TestTrain)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aghinsa/Documents/workspace/prep/global/dffml/dffml/util/asynctestcase.py", line 46, in run_it
    result = self.loop.run_until_complete(coro(*args, **kwargs))
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/home/aghinsa/Documents/workspace/prep/global/dffml/tests/test_cli.py", line 399, in test_run
    Train, "arg_features", Train.arg_features.modify(type=feature_load)
AttributeError: type object 'Train' has no attribute 'arg_features'

----------------------------------------------------------------------
Ran 12 tests in 0.037s

FAILED (errors=6)
Test failed: <unittest.runner.TextTestResult run=12 errors=6 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=12 errors=6 failures=0>

```

**Comment by aghinsa** [comment]
from the looks of it, [TestEvaluateAll](https://github.com/intel/dffml/blob/39916228016385e72a3539fa6ac2f39a790dcd1f/tests/test_cli.py#L350),[TestEvaluateRepo](https://github.com/intel/dffml/blob/39916228016385e72a3539fa6ac2f39a790dcd1f/tests/test_cli.py#L374) doesn't depend on any model ,did i get that wrong?if not,then how do we pass model.config?
