### ISSUE TITLE
model: scikit: ModuleNotFoundError: No module named 'dffml.repo'

### ISSUE THREAD

**Issue by sk-ip** [intel/dffml#445]
## Describe the bug
Got `ModuleNotFoundError: No module named 'dffml.repo'` error
## Steps To Reproduce
run the example usage of Linear Regression Model using python API code [here](https://intel.github.io/dffml/master/plugins/dffml_model.html#dffml-model-scikit)
## Expected behavior
Should have got the predicted values
## Logs or Screenshots
```
gitpod /workspace/dffml $ python sample.py 
Traceback (most recent call last):
  File "sample.py", line 3, in <module>
    from dffml_model_scikit import LinearRegressionModel
  File "/home/gitpod/.pyenv/versions/3.7.6/lib/python3.7/site-packages/dffml_model_scikit/__init__.py", line 288, in <module>
    from .scikit_models import *
  File "/home/gitpod/.pyenv/versions/3.7.6/lib/python3.7/site-packages/dffml_model_scikit/scikit_models.py", line 59, in <module>
    from dffml_model_scikit.scikit_base import (
  File "/home/gitpod/.pyenv/versions/3.7.6/lib/python3.7/site-packages/dffml_model_scikit/scikit_base.py", line 17, in <module>
    from dffml.repo import Repo
ModuleNotFoundError: No module named 'dffml.repo'
gitpod /workspace/dffml $ 
```
## Packages in use and versions

- dffml==0.3.4
- dffml-model-scikit=0.0.5

**Comment by pdxjohnny** [comment]
Ooops!! Thank you! I forgot to bump all the versions of the dependencies :grimacing:

**Comment by pdxjohnny** [comment]
Thank you!!! Fixed.
