### ISSUE TITLE
Tensorflow_hub / scratch: ubuntu: python api does not run successfully as scikit does

### ISSUE THREAD

**Issue by TakshKamlesh** [intel/dffml#537]
## 'module' object is not callable

This error shows when you run scratch or tensorflow hub models in python. But works perfectly for scikit

## Steps To Reproduce

```python
from dffml import CSVSource, Features, DefFeature
from dffml.noasync import train, accuracy, predict
from dffml_model_tensorflow_hub import text_classifier


model = text_classifier(
features = Features(
DefFeature("Sentence" , str , 1),
),
    predict = DefFeature('Sentiment', int ,1)

)
train(model , {'I hate you!!' , 2} , {'Okay , so what do we do now?' , 0} ,
     {'I find this dish incredibly tasty' , 1} , {'This movie is horrible' , 2} ,
     {'You look beautiful' , 1} , {'I think your project could use more collabaration' , 0}
     ,{'I cannot see any effort put here' ,2} , {'This is exactly what I wanted',  1})

print(accuracy(model,
              {'This is horrific', 2} , {'Its okay never mind' , 0} , {'This time could not have been better' , 1}))

for i, features, prediction in predict(
    model,
    {'This is horrific'} , {'Its okay never mind'} , {'This time could not have been better'}
):
    features["Sentiment"] = prediction["Sentiment"]["value"]
    print(features)
```

## Packages in use and versions

- dffml==0.3.5

**Comment by pdxjohnny** [comment]
We need a python example for that one :(

You need to change the import, and you need to pass key value `dict`s to the ml functions.

```pythonfrom dffml import CSVSource, Features, DefFeature
from dffml.noasync import train, accuracy, predict
from dffml_model_tensorflow_hub.text_classifier import TextClassificationModel


model = TextClassificationModel(
    features=Features(DefFeature("Sentence", str, 1)),
    predict=DefFeature("Sentiment", int, 1),
    classifications=[0, 1, 2],
)

train(
    model,
    {"Sentence": "I hate you!!", "Sentiment": 2},
    {"Sentence": "Okay , so what do we do now?", "Sentiment": 0},
    {"Sentence": "I find this dish incredibly tasty", "Sentiment": 1},
    {"Sentence": "This movie is horrible", "Sentiment": 2},
    {"Sentence": "You look beautiful", "Sentiment": 1},
    {"Sentence": "I think your project could use more collabaration", "Sentiment": 0},
    {"Sentence": "I cannot see any effort put here", "Sentiment": 2},
    {"Sentence": "This is exactly what I wanted", "Sentiment": 1},
)

print(
    accuracy(
        model,
        {"Sentence": "This is horrific", "Sentiment": 2},
        {"Sentence": "Its okay never mind", "Sentiment": 0},
        {"Sentence": "This time could not have been better", "Sentiment": 1},
    )
)

for i, features, prediction in predict(
    model,
    {"Sentence": "This is horrific"},
    {"Sentence": "Its okay never mind"},
    {"Sentence": "This time could not have been better"},
):
    features["Sentiment"] = prediction["Sentiment"]["value"]
    print(features)
```

I'm getting an error, I'm a bit braindead right now. @0dust can probably help get you the rest of the way.

```
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    {"Sentence": "This is exactly what I wanted", "Sentiment": 1},
  File "/home/pdxjohnny/Documents/python/dffml/dffml/noasync.py", line 7, in train
    return asyncio.run(high_level.train(*args, **kwargs))
  File "/home/pdxjohnny/.pyenv/versions/3.7.2/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/home/pdxjohnny/.pyenv/versions/3.7.2/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/pdxjohnny/Documents/python/dffml/dffml/high_level.py", line 89, in train
    return await mctx.train(sctx)
  File "/home/pdxjohnny/Documents/python/dffml/model/tensorflow_hub/dffml_model_tensorflow_hub/text_classifier.py", line 263, in train
    x, y = await self.train_data_generator(sources)
  File "/home/pdxjohnny/Documents/python/dffml/model/tensorflow_hub/dffml_model_tensorflow_hub/text_classifier.py", line 207, in train_data_generator
    raise ValueError("No records to train on")
ValueError: No records to train on
```

**Comment by 0dust** [comment]
@pdxjohnny Sure!

**Comment by 0dust** [comment]
@TakshKamlesh @pdxjohnny We need to specify the `clstype` (Data Type of classification values) which is `int` here.
So the example should be:
```python
import logging
logging.basicConfig(level=logging.DEBUG)

from dffml import CSVSource, Features, DefFeature
from dffml.noasync import train, accuracy, predict
from dffml_model_tensorflow_hub.text_classifier import TextClassificationModel


model = TextClassificationModel(
    features=Features(DefFeature("Sentence", str, 1)),
    predict=DefFeature("Sentiment", int, 1),
    classifications=[0, 1, 2],
    clstype = int
)

train(
    model,
    {"Sentence": "I hate you!!", "Sentiment": 2},
    {"Sentence": "Okay , so what do we do now?", "Sentiment": 0},
    {"Sentence": "I find this dish incredibly tasty", "Sentiment": 1},
    {"Sentence": "This movie is horrible", "Sentiment": 2},
    {"Sentence": "You look beautiful", "Sentiment": 1},
    {"Sentence": "I think your project could use more collabaration", "Sentiment": 0},
    {"Sentence": "I cannot see any effort put here", "Sentiment": 2},
    {"Sentence": "This is exactly what I wanted", "Sentiment": 1},
)

print(
    accuracy(
        model,
        {"Sentence": "This is horrific", "Sentiment": 2},
        {"Sentence": "Its okay never mind", "Sentiment": 0},
        {"Sentence": "This time could not have been better", "Sentiment": 1},
    )
)

for i, features, prediction in predict(
    model,
    {"Sentence": "This is horrific"},
    {"Sentence": "Its okay never mind"},
    {"Sentence": "This time could not have been better"},
):
    features["Sentiment"] = prediction["Sentiment"]["value"]
    print(features)
```
