### ISSUE TITLE
ci: transformers range issue when building docs for previous release

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#691]
```
2020-06-02T16:56:03.3127332Z + ./scripts/docs.sh
2020-06-02T16:56:06.1827511Z Traceback (most recent call last):
2020-06-02T16:56:06.1828487Z   File "scripts/docs.py", line 279, in <module>
2020-06-02T16:56:06.1829040Z     main()
2020-06-02T16:56:06.1829515Z   File "scripts/docs.py", line 273, in main
2020-06-02T16:56:06.1829969Z     + gen_docs(entrypoint, modules)
2020-06-02T16:56:06.1830436Z   File "scripts/docs.py", line 167, in gen_docs
2020-06-02T16:56:06.1830839Z     cls = i.load()
2020-06-02T16:56:06.1832139Z   File "/usr/share/miniconda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2462, in load
2020-06-02T16:56:06.1832653Z     return self.resolve()
2020-06-02T16:56:06.1833640Z   File "/usr/share/miniconda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2468, in resolve
2020-06-02T16:56:06.1834313Z     module = __import__(self.module_name, fromlist=['__name__'], level=0)
2020-06-02T16:56:06.1834834Z   File "/home/runner/work/dffml/dffml/model/transformers/dffml_model_transformers/ner/ner_model.py", line 52, in <module>
2020-06-02T16:56:06.1835198Z     (),
2020-06-02T16:56:06.1835679Z   File "/home/runner/work/dffml/dffml/model/transformers/dffml_model_transformers/ner/ner_model.py", line 50, in <genexpr>
2020-06-02T16:56:06.1836098Z     for conf in (BertConfig, RobertaConfig, DistilBertConfig)
2020-06-02T16:56:06.1836829Z AttributeError: type object 'BertConfig' has no attribute 'pretrained_config_archive_map'
```

**Comment by pdxjohnny** [comment]
Fixed by adding a commit to the 0.3.7 tag
