### ISSUE TITLE
base: Not able to pass second level source config through CLI

### ISSUE THREAD

**Issue by sakshamarora1** [intel/dffml#728]
## Steps To Reproduce

```console
dffml list records \
    -sources f=df \
    -source-f-source csv -source-filename train.csv \
    -log debug
DEBUG:dffml.JSONSource:FileSourceConfig(filename=PosixPath('~/.cache/dffml.json'), tag='untagged', readwrite=False, allowempty=False)
DEBUG:dffml.cli.list.ListRecords:Setting sources = [<class 'dffml.base.DataFlowSource'>]
DEBUG:dffml.cli.list.ListRecords:Setting pretty = False
Traceback (most recent call last):
  File "/home/tron/Desktop/dffml/dffml/base.py", line 507, in config
    config, *above, *cls.add_label()
  File "/home/tron/Desktop/dffml/dffml/base.py", line 517, in withconfig
    return cls(cls.config(config, *above))
  File "/home/tron/Desktop/dffml/dffml/base.py", line 502, in config
    config, above, field.name
  File "/home/tron/Desktop/dffml/dffml/base.py", line 461, in config_get
    return convert_value(arg, value)
  File "/home/tron/Desktop/dffml/dffml/base.py", line 145, in convert_value
    raise MissingConfig
dffml.base.MissingConfig: CSVSource missing 'filename' from source.f.source.csv

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tron/.local/bin/dffml", line 33, in <module>
    sys.exit(load_entry_point('dffml', 'console_scripts', 'dffml')())
  File "/home/tron/Desktop/dffml/dffml/util/cli/cmd.py", line 273, in main
    result = loop.run_until_complete(cls._main(*argv[1:]))
  File "/home/tron/anaconda3/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/home/tron/Desktop/dffml/dffml/util/cli/cmd.py", line 234, in _main
    result = await cls.cli(*args)
  File "/home/tron/Desktop/dffml/dffml/util/cli/cmd.py", line 219, in cli
    cmd = args.cmd(**cls.sanitize_args(vars(args)))
  File "/home/tron/Desktop/dffml/dffml/util/cli/cmds.py", line 58, in __init__
    self.sources[i] = self.sources[i].withconfig(self.extra_config)
  File "/home/tron/Desktop/dffml/dffml/base.py", line 517, in withconfig
    return cls(cls.config(config, *above))
  File "/home/tron/Desktop/dffml/dffml/base.py", line 511, in config
    config, *above, *cls.add_label()[:-1]
  File "/home/tron/Desktop/dffml/dffml/base.py", line 517, in withconfig
    return cls(cls.config(config, *above))
  File "/home/tron/Desktop/dffml/dffml/base.py", line 502, in config
    config, above, field.name
  File "/home/tron/Desktop/dffml/dffml/base.py", line 461, in config_get
    return convert_value(arg, value)
  File "/home/tron/Desktop/dffml/dffml/base.py", line 145, in convert_value
    raise MissingConfig
dffml.base.MissingConfig: CSVSource missing 'filename' from source.source.csv

```

**Comment by sakshamarora1** [comment]
I was missing the second `source` entry. My bad! :sweat_smile:
Corrected command :-
```
dffml list records \
    -sources f=df \
    -source-source csv -source-source-filename train.csv \
    ...-source-dataflow and -source-features...
    -log debug
```
