### ISSUE TITLE
model: tensorflow: scipy is 1.5.0 but tensorflow requires scipy 1.4.1

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#737]
We should figure out what is causing scipy to be 1.5.0

```
2020-06-22T02:34:19.3178721Z Successfully installed GitPython-3.1.3 Keras-2.4.2 PyMySQL-0.9.2 PyYAML-5.3.1 absl-py-0.9.0 aiohttp-3.6.2 aiohttp-cors-0.7.0 aiomysql-0.0.20 astunparse-1.6.3 async-timeout-3.0.1 bandit-1.6.2 cachetools-4.1.0 dffml-config-png dffml-config-yaml dffml-feature-auth dffml-feature-git-0.2.7 dffml-model-daal4py dffml-model-scikit dffml-model-scratch dffml-model-tensorflow dffml-model-tensorflow-hub dffml-model-transformers dffml-model-vowpalWabbit dffml-operations-binsec dffml-operations-deploy dffml-operations-image dffml-service-http dffml-source-mysql dparse-0.5.1 fastprogress-0.2.3 filelock-3.0.12 gast-0.3.3 gitdb-4.0.5 google-auth-1.18.0 google-auth-oauthlib-0.4.1 google-pasta-0.2.0 grpcio-1.29.0 h5py-2.10.0 joblib-0.15.1 keras-preprocessing-1.1.2 markdown-3.2.2 multidict-4.7.6 oauthlib-3.1.0 opencv-python-4.2.0.34 opt-einsum-3.2.1 pandas-1.0.5 pbr-5.4.5 protobuf-3.12.2 pyasn1-0.4.8 pyasn1-modules-0.2.8 pyelftools-0.26 python-dateutil-2.8.1 requests-oauthlib-1.3.0 rpmfile-1.0.2 rsa-4.6 sacremoses-0.0.43 safety-1.9.0 scikit-learn-0.23.1 scipy-1.5.0 sentencepiece-0.1.91 seqeval-0.0.12 shouldi smmap-3.0.4 stevedore-2.0.0 tensorboard-2.2.2 tensorboard-plugin-wit-1.6.0.post3 tensorflow-2.2.0 tensorflow-estimator-2.2.0 tensorflow-hub-0.8.0 termcolor-1.1.0 threadpoolctl-2.1.0 tokenizers-0.7.0 transformers-2.11.0 werkzeug-1.0.1 wrapt-1.12.1 yarl-1.4.2
2020-06-22T02:34:19.3298534Z + run_plugin_examples
2020-06-22T02:34:19.3299363Z + '[' '!' -d /home/runner/work/dffml/dffml/./examples ']'
2020-06-22T02:34:19.3299782Z + cd /home/runner/work/dffml/dffml/./examples
2020-06-22T02:34:19.3300468Z + '[' -f requirements.txt ']'
2020-06-22T02:34:19.3300736Z + python3.7 -m pip install -r requirements.txt
2020-06-22T02:34:19.9796015Z Collecting aiosqlite>=0.10.0
2020-06-22T02:34:20.0325353Z   Downloading aiosqlite-0.13.0-py3-none-any.whl (12 kB)
2020-06-22T02:34:20.5086068Z Installing collected packages: aiosqlite
2020-06-22T02:34:20.5782777Z Successfully installed aiosqlite-0.13.0
2020-06-22T02:34:20.6791649Z + python3.7 -m unittest discover -v
2020-06-22T02:34:23.7903122Z test_shell (MNIST.test_mnist.TestMNIST) ... Error loading dffml.model.tfdnnc: Traceback (most recent call last):
2020-06-22T02:34:23.7904474Z   File "/home/runner/work/dffml/dffml/dffml/util/entrypoint.py", line 160, in load
2020-06-22T02:34:23.7905059Z     loaded = i.load()
2020-06-22T02:34:23.7906321Z   File "/usr/share/miniconda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2460, in load
2020-06-22T02:34:23.7906868Z     self.require(*args, **kwargs)
2020-06-22T02:34:23.7907968Z   File "/usr/share/miniconda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2483, in require
2020-06-22T02:34:23.7908389Z     items = working_set.resolve(reqs, env, installer, extras=self.extras)
2020-06-22T02:34:23.7909197Z   File "/usr/share/miniconda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
2020-06-22T02:34:23.7909621Z     raise VersionConflict(dist, req).with_context(dependent_req)
2020-06-22T02:34:23.7910273Z pkg_resources.ContextualVersionConflict: (scipy 1.5.0 (/usr/share/miniconda/lib/python3.7/site-packages), Requirement.parse('scipy==1.4.1; python_version >= "3"'), {'tensorflow'})
2020-06-22T02:34:23.7993014Z Traceback (most recent call last):
2020-06-22T02:34:23.7993706Z   File "/usr/share/miniconda/bin/dffml", line 33, in <module>
2020-06-22T02:34:23.8003177Z     sys.exit(load_entry_point('dffml', 'console_scripts', 'dffml')())
2020-06-22T02:34:23.8003844Z   File "/home/runner/work/dffml/dffml/dffml/util/cli/cmd.py", line 273, in main
2020-06-22T02:34:23.8004170Z     result = loop.run_until_complete(cls._main(*argv[1:]))
2020-06-22T02:34:23.8004576Z   File "/usr/share/miniconda/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
2020-06-22T02:34:23.8004864Z     return future.result()
2020-06-22T02:34:23.8005226Z   File "/home/runner/work/dffml/dffml/dffml/util/cli/cmd.py", line 234, in _main
2020-06-22T02:34:23.8005514Z     result = await cls.cli(*args)
2020-06-22T02:34:23.8005910Z   File "/home/runner/work/dffml/dffml/dffml/util/cli/cmd.py", line 206, in cli
2020-06-22T02:34:23.8013947Z     parser, (args, unknown) = await cls.parse_args(*args)
2020-06-22T02:34:23.8014235Z   File "/home/runner/work/dffml/dffml/dffml/util/cli/cmd.py", line 195, in parse_args
2020-06-22T02:34:23.8014399Z     return parser, parser.parse_known_args(args)
2020-06-22T02:34:23.8014618Z   File "/usr/share/miniconda/lib/python3.7/argparse.py", line 1787, in parse_known_args
2020-06-22T02:34:23.8014788Z     namespace, args = self._parse_known_args(args, namespace)
2020-06-22T02:34:23.8015009Z   File "/usr/share/miniconda/lib/python3.7/argparse.py", line 1975, in _parse_known_args
2020-06-22T02:34:23.8015167Z     positionals_end_index = consume_positionals(start_index)
2020-06-22T02:34:23.8015385Z   File "/usr/share/miniconda/lib/python3.7/argparse.py", line 1952, in consume_positionals
2020-06-22T02:34:23.8015536Z     take_action(action, args)
2020-06-22T02:34:23.8015794Z   File "/usr/share/miniconda/lib/python3.7/argparse.py", line 1861, in take_action
2020-06-22T02:34:23.8015953Z     action(self, namespace, argument_values, option_string)
2020-06-22T02:34:23.8016148Z   File "/usr/share/miniconda/lib/python3.7/argparse.py", line 1158, in __call__
2020-06-22T02:34:23.8016305Z     subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
2020-06-22T02:34:23.8016507Z   File "/usr/share/miniconda/lib/python3.7/argparse.py", line 1787, in parse_known_args
2020-06-22T02:34:23.8016666Z     namespace, args = self._parse_known_args(args, namespace)
2020-06-22T02:34:23.8016862Z   File "/usr/share/miniconda/lib/python3.7/argparse.py", line 1993, in _parse_known_args
2020-06-22T02:34:23.8017181Z     start_index = consume_optional(start_index)
2020-06-22T02:34:23.8017380Z   File "/usr/share/miniconda/lib/python3.7/argparse.py", line 1933, in consume_optional
2020-06-22T02:34:23.8017538Z     take_action(action, args, option_string)
2020-06-22T02:34:23.8018390Z   File "/usr/share/miniconda/lib/python3.7/argparse.py", line 1845, in take_action
2020-06-22T02:34:23.8018631Z     argument_values = self._get_values(action, argument_strings)
2020-06-22T02:34:23.8019107Z   File "/usr/share/miniconda/lib/python3.7/argparse.py", line 2376, in _get_values
2020-06-22T02:34:23.8019278Z     value = self._get_value(action, arg_string)
2020-06-22T02:34:23.8019496Z   File "/usr/share/miniconda/lib/python3.7/argparse.py", line 2409, in _get_value
2020-06-22T02:34:23.8019671Z     result = type_func(arg_string)
2020-06-22T02:34:23.8019981Z   File "/home/runner/work/dffml/dffml/dffml/util/entrypoint.py", line 160, in load
2020-06-22T02:34:23.8020184Z     loaded = i.load()
2020-06-22T02:34:23.8020840Z   File "/usr/share/miniconda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2460, in load
2020-06-22T02:34:23.8021027Z     self.require(*args, **kwargs)
2020-06-22T02:34:23.8021982Z   File "/usr/share/miniconda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2483, in require
2020-06-22T02:34:23.8022172Z     items = working_set.resolve(reqs, env, installer, extras=self.extras)
2020-06-22T02:34:23.8022820Z   File "/usr/share/miniconda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
2020-06-22T02:34:23.8023052Z     raise VersionConflict(dist, req).with_context(dependent_req)
2020-06-22T02:34:23.8023499Z pkg_resources.ContextualVersionConflict: (scipy 1.5.0 (/usr/share/miniconda/lib/python3.7/site-packages), Requirement.parse('scipy==1.4.1; python_version >= "3"'), {'tensorflow'})
2020-06-22T02:34:23.8501587Z ERROR
```

**Comment by sudharsana-kjl** [comment]
scipy had a release on June 21,2020:
https://pypi.org/project/scipy/#history

with the help of ```pipdeptree``` package, we could see the following dependency:
![image](https://user-images.githubusercontent.com/10111093/85520164-2a1d6680-b620-11ea-9a9f-771f6b0a01bb.png)

scikit-learn installed the latest version of scipy which is not compatible with tensorflow.

**Comment by pdxjohnny** [comment]
This bug is no longer present in our CI, great job finding this @sudharsana-kjl!!
