### ISSUE TITLE
examples: MNIST: DefinitionMissing exception while resolving resize.outputs, missing resize.outputs.result

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#741]
```
2020-06-24T21:19:38.2097548Z Traceback (most recent call last):
2020-06-24T21:19:38.2098542Z   File "/usr/share/miniconda/bin/dffml", line 33, in <module>
2020-06-24T21:19:38.2099663Z     sys.exit(load_entry_point('dffml', 'console_scripts', 'dffml')())
2020-06-24T21:19:38.2100304Z   File "/home/runner/work/dffml/dffml/dffml/util/cli/cmd.py", line 273, in main
2020-06-24T21:19:38.2100759Z     result = loop.run_until_complete(cls._main(*argv[1:]))
2020-06-24T21:19:38.2101347Z   File "/usr/share/miniconda/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
2020-06-24T21:19:38.2101784Z     return future.result()
2020-06-24T21:19:38.2102341Z   File "/home/runner/work/dffml/dffml/dffml/util/cli/cmd.py", line 234, in _main
2020-06-24T21:19:38.2102773Z     result = await cls.cli(*args)
2020-06-24T21:19:38.2103424Z   File "/home/runner/work/dffml/dffml/dffml/util/cli/cmd.py", line 220, in cli
2020-06-24T21:19:38.2108592Z     return await cmd.do_run()
2020-06-24T21:19:38.2112982Z   File "/home/runner/work/dffml/dffml/dffml/util/cli/cmd.py", line 200, in do_run
2020-06-24T21:19:38.2113496Z     return [res async for res in self.run()]
2020-06-24T21:19:38.2114029Z   File "/home/runner/work/dffml/dffml/dffml/util/cli/cmd.py", line 200, in <listcomp>
2020-06-24T21:19:38.2114473Z     return [res async for res in self.run()]
2020-06-24T21:19:38.2114982Z   File "/home/runner/work/dffml/dffml/dffml/cli/ml.py", line 69, in run
2020-06-24T21:19:38.2115419Z     self.model, self.sources, update=self.update, keep_record=True
2020-06-24T21:19:38.2116018Z   File "/home/runner/work/dffml/dffml/dffml/high_level.py", line 503, in predict
2020-06-24T21:19:38.2123617Z     async with sources() as sctx, model() as mctx:
2020-06-24T21:19:38.2124036Z   File "/home/runner/work/dffml/dffml/dffml/util/asynchelper.py", line 48, in __aenter__
2020-06-24T21:19:38.2124387Z     self.data.append(await self.__stack.enter_async_context(citem))
2020-06-24T21:19:38.2124735Z   File "/usr/share/miniconda/lib/python3.7/contextlib.py", line 570, in enter_async_context
2020-06-24T21:19:38.2125033Z     result = await _cm_type.__aenter__(cm)
2020-06-24T21:19:38.2125355Z   File "/home/runner/work/dffml/dffml/dffml/source/df.py", line 54, in __aenter__
2020-06-24T21:19:38.2125628Z     self.parent.config.dataflow = DataFlow._fromdict(**exported)
2020-06-24T21:19:38.2125955Z   File "/home/runner/work/dffml/dffml/dffml/df/types.py", line 639, in _fromdict
2020-06-24T21:19:38.2126217Z     kwargs.update(cls._resolve(kwargs))
2020-06-24T21:19:38.2126701Z   File "/home/runner/work/dffml/dffml/dffml/df/types.py", line 791, in _resolve
2020-06-24T21:19:38.2126977Z     f"While resolving {instance_name}.{arg}, missing {definition_name}"
2020-06-24T21:19:38.2127236Z dffml.df.types.DefinitionMissing: While resolving resize.outputs, missing resize.outputs.result
```

**Comment by sakshamarora1** [comment]
Related: #735 
This is because we haven't updated the definition names in the `create dataflow` command to their shorthand names.
