### ISSUE TITLE
model: transformers: Update for 3.0.1 compatibility

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#763]
```
2020-07-06T18:06:40.9615398Z ======================================================================
2020-07-06T18:06:40.9615784Z ERROR: test_run (tests.test_ner_integration.TestNER)
2020-07-06T18:06:40.9616274Z ----------------------------------------------------------------------
2020-07-06T18:06:40.9616550Z Traceback (most recent call last):
2020-07-06T18:06:40.9616873Z   File "/home/runner/work/dffml/dffml/dffml/util/asynctestcase.py", line 69, in run_it
2020-07-06T18:06:40.9617174Z     result = self.loop.run_until_complete(coro(*args, **kwargs))
2020-07-06T18:06:40.9617520Z   File "/usr/share/miniconda/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
2020-07-06T18:06:40.9617974Z     return future.result()
2020-07-06T18:06:40.9618311Z   File "/home/runner/work/dffml/dffml/model/transformers/tests/test_ner_integration.py", line 90, in test_run
2020-07-06T18:06:40.9618611Z     train_data_filename,
2020-07-06T18:06:40.9618923Z   File "/home/runner/work/dffml/dffml/dffml/util/cli/cmd.py", line 220, in cli
2020-07-06T18:06:40.9619211Z     return await cmd.do_run()
2020-07-06T18:06:40.9619631Z   File "/home/runner/work/dffml/dffml/dffml/util/cli/cmd.py", line 202, in do_run
2020-07-06T18:06:40.9619921Z     return await self.run()
2020-07-06T18:06:40.9620234Z   File "/home/runner/work/dffml/dffml/dffml/cli/ml.py", line 40, in run
2020-07-06T18:06:40.9620528Z     return await train(self.model, self.sources)
2020-07-06T18:06:40.9620844Z   File "/home/runner/work/dffml/dffml/dffml/high_level.py", line 380, in train
2020-07-06T18:06:40.9621129Z     return await mctx.train(sctx)
2020-07-06T18:06:40.9621668Z   File "/home/runner/work/dffml/dffml/model/transformers/dffml_model_transformers/ner/ner_model.py", line 381, in train
2020-07-06T18:06:40.9622020Z     trainer.train()
2020-07-06T18:06:40.9622610Z   File "/usr/share/miniconda/lib/python3.7/site-packages/transformers/trainer_tf.py", line 410, in train
2020-07-06T18:06:40.9623020Z     if self.args.past_index >= 0:
2020-07-06T18:06:40.9623497Z AttributeError: 'NERModelConfig' object has no attribute 'past_index'
```

**Comment by pdxjohnny** [comment]
Ping @0dust
