### ISSUE TITLE
model: daal4py: Pip fails to install daal4py during dffml installation.

### ISSUE THREAD

**Issue by mHash1m** [intel/dffml#766]
## Describe the bug

I suppose dffml tries to install daal4py using pip, whereas daal4py isn't available on pip.

## Steps To Reproduce
running:

`dffml service dev install -user`
or
`python3.7 -m pip install --prefix=~/.local -e model/daal4py`

## Logs

```
ERROR: Could not find a version that satisfies the requirement daal4py>=0.2020.0 (from dffml-model-daal4py==0.0.1) (from versions: none)
ERROR: No matching distribution found for daal4py>=0.2020.0 (from dffml-model-daal4py==0.0.1)
Traceback (most recent call last):
  File "/home/hash1m/.local/bin/dffml", line 33, in <module>
    sys.exit(load_entry_point('dffml', 'console_scripts', 'dffml')())
  File "/home/hash1m/dffml/dffml/util/cli/cmd.py", line 273, in main
    result = loop.run_until_complete(cls._main(*argv[1:]))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/home/hash1m/dffml/dffml/util/cli/cmd.py", line 234, in _main
    result = await cls.cli(*args)
  File "/home/hash1m/dffml/dffml/util/cli/cmd.py", line 220, in cli
    return await cmd.do_run()
  File "/home/hash1m/dffml/dffml/util/cli/cmd.py", line 202, in do_run
    return await self.run()
  File "/home/hash1m/dffml/dffml/service/dev.py", line 340, in run
    raise RuntimeError("pip failed to install dependencies")
RuntimeError: pip failed to install dependencies

```

## Misc Notes
Everything seems okay debugging with:

```
docker run --rm -ti -u $(id -u):$(id -g) \
    -e LOGGING=debug \
    -e USER=$USER \
    -v $HOME/.cache/pip:/home/$USER/.cache/pip -w /usr/src/dffml \
    -v $PWD:/usr/src/dffml -w /usr/src/dffml \
    --entrypoint .ci/docker-entrypoint.sh python:3.7 .
```

**Comment by pdxjohnny** [comment]
The workaround here is to install with `conda`

https://github.com/intel/dffml/blob/1b0ede6dbd76772a544b5febff0c006cca939ecd/.ci/deps.sh#L83

**Comment by mHash1m** [comment]
@pdxjohnny Yes but does this make conda a dependency of DFFML? Should it be on the documentation? Or do we wait to hear on the PyPi release

**Comment by mHash1m** [comment]
@pdxjohnny  Yes but I'm not sure how to enforce this on the dffml installation and stop it from looking on PyPi.

**Comment by pdxjohnny** [comment]
If it's already installed with conda, then the user shouldn't be getting this message, or is that not the case?

**Comment by mHash1m** [comment]
no, it throws the same error with pre-installed daal4py.
