### ISSUE TITLE
model: autosklearn: Incompatable with version 0.10.0

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#858]
```
2020-09-26T21:08:58.5863710Z + cd /home/runner/work/dffml/dffml/model/autosklearn
2020-09-26T21:08:58.5864710Z + python3.7 -m pip install -U -e .
2020-09-26T21:08:59.0360700Z Obtaining file:///home/runner/work/dffml/dffml/model/autosklearn
2020-09-26T21:08:59.0386238Z   Installing build dependencies: started
2020-09-26T21:09:00.9133353Z   Installing build dependencies: finished with status 'done'
2020-09-26T21:09:00.9142194Z   Getting requirements to build wheel: started
2020-09-26T21:09:01.1390438Z   Getting requirements to build wheel: finished with status 'done'
2020-09-26T21:09:01.1418931Z     Preparing wheel metadata: started
2020-09-26T21:09:01.3832461Z     Preparing wheel metadata: finished with status 'done'
2020-09-26T21:09:01.4055055Z Requirement already satisfied, skipping upgrade: dffml>=0.3.7 in /home/runner/work/dffml/dffml (from dffml-model-autosklearn==0.0.1) (0.3.7)
2020-09-26T21:09:01.4990404Z Collecting auto-sklearn>=0.7.0
2020-09-26T21:09:01.5584926Z   Downloading auto-sklearn-0.10.0.tar.gz (4.1 MB)
2020-09-26T21:09:02.6360479Z Requirement already satisfied, skipping upgrade: setuptools in /usr/share/miniconda/lib/python3.7/site-packages (from auto-sklearn>=0.7.0->dffml-model-autosklearn==0.0.1) (50.3.0)
2020-09-26T21:09:02.6572504Z Requirement already satisfied, skipping upgrade: numpy>=1.9.0 in /usr/share/miniconda/lib/python3.7/site-packages (from auto-sklearn>=0.7.0->dffml-model-autosklearn==0.0.1) (1.19.2)
2020-09-26T21:09:02.6586604Z Requirement already satisfied, skipping upgrade: scipy>=0.14.1 in /usr/share/miniconda/lib/python3.7/site-packages (from auto-sklearn>=0.7.0->dffml-model-autosklearn==0.0.1) (1.5.2)
2020-09-26T21:09:02.6611420Z Requirement already satisfied, skipping upgrade: joblib in /usr/share/miniconda/lib/python3.7/site-packages (from auto-sklearn>=0.7.0->dffml-model-autosklearn==0.0.1) (0.16.0)
2020-09-26T21:09:02.6627202Z Requirement already satisfied, skipping upgrade: scikit-learn<0.23,>=0.22.0 in /usr/share/miniconda/lib/python3.7/site-packages (from auto-sklearn>=0.7.0->dffml-model-autosklearn==0.0.1) (0.22.2.post1)
2020-09-26T21:09:02.6687993Z Requirement already satisfied, skipping upgrade: dask in /usr/share/miniconda/lib/python3.7/site-packages (from auto-sklearn>=0.7.0->dffml-model-autosklearn==0.0.1) (2.28.0)
2020-09-26T21:09:02.6945331Z Requirement already satisfied, skipping upgrade: distributed in /usr/share/miniconda/lib/python3.7/site-packages (from auto-sklearn>=0.7.0->dffml-model-autosklearn==0.0.1) (2.28.0)
2020-09-26T21:09:02.7084502Z Requirement already satisfied, skipping upgrade: lockfile in /usr/share/miniconda/lib/python3.7/site-packages (from auto-sklearn>=0.7.0->dffml-model-autosklearn==0.0.1) (0.12.2)
2020-09-26T21:09:02.7095574Z Requirement already satisfied, skipping upgrade: pyyaml in /usr/share/miniconda/lib/python3.7/site-packages (from auto-sklearn>=0.7.0->dffml-model-autosklearn==0.0.1) (5.3.1)
2020-09-26T21:09:02.7119766Z Requirement already satisfied, skipping upgrade: pandas<1.0 in /usr/share/miniconda/lib/python3.7/site-packages (from auto-sklearn>=0.7.0->dffml-model-autosklearn==0.0.1) (0.25.3)
2020-09-26T21:09:02.7182289Z Requirement already satisfied, skipping upgrade: liac-arff in /usr/share/miniconda/lib/python3.7/site-packages (from auto-sklearn>=0.7.0->dffml-model-autosklearn==0.0.1) (2.5.0)
2020-09-26T21:09:02.7197159Z Requirement already satisfied, skipping upgrade: ConfigSpace<0.5,>=0.4.14 in /usr/share/miniconda/lib/python3.7/site-packages (from auto-sklearn>=0.7.0->dffml-model-autosklearn==0.0.1) (0.4.15)
2020-09-26T21:09:02.7227623Z Requirement already satisfied, skipping upgrade: pynisher>=0.4.2 in /usr/share/miniconda/lib/python3.7/site-packages (from auto-sklearn>=0.7.0->dffml-model-autosklearn==0.0.1) (0.6.0)
2020-09-26T21:09:02.7257632Z Requirement already satisfied, skipping upgrade: pyrfr<0.9,>=0.7 in /usr/share/miniconda/lib/python3.7/site-packages (from auto-sklearn>=0.7.0->dffml-model-autosklearn==0.0.1) (0.8.0)
2020-09-26T21:09:02.7267723Z Requirement already satisfied, skipping upgrade: smac<0.14,>=0.13 in /usr/share/miniconda/lib/python3.7/site-packages (from auto-sklearn>=0.7.0->dffml-model-autosklearn==0.0.1) (0.13.0)
2020-09-26T21:09:02.7479249Z Requirement already satisfied, skipping upgrade: tornado>=5; python_version < "3.8" in /usr/share/miniconda/lib/python3.7/site-packages (from distributed->auto-sklearn>=0.7.0->dffml-model-autosklearn==0.0.1) (6.0.4)
2020-09-26T21:09:02.7490477Z Requirement already satisfied, skipping upgrade: toolz>=0.8.2 in /usr/share/miniconda/lib/python3.7/site-packages (from distributed->auto-sklearn>=0.7.0->dffml-model-autosklearn==0.0.1) (0.11.1)
2020-09-26T21:09:02.7504607Z Requirement already satisfied, skipping upgrade: tblib>=1.6.0 in /usr/share/miniconda/lib/python3.7/site-packages (from distributed->auto-sklearn>=0.7.0->dffml-model-autosklearn==0.0.1) (1.7.0)
2020-09-26T21:09:02.7534744Z Requirement already satisfied, skipping upgrade: click>=6.6 in /usr/share/miniconda/lib/python3.7/site-packages (from distributed->auto-sklearn>=0.7.0->dffml-model-autosklearn==0.0.1) (7.1.2)
2020-09-26T21:09:02.7549371Z Requirement already satisfied, skipping upgrade: zict>=0.1.3 in /usr/share/miniconda/lib/python3.7/site-packages (from distributed->auto-sklearn>=0.7.0->dffml-model-autosklearn==0.0.1) (2.0.0)
2020-09-26T21:09:02.7567283Z Requirement already satisfied, skipping upgrade: msgpack>=0.6.0 in /usr/share/miniconda/lib/python3.7/site-packages (from distributed->auto-sklearn>=0.7.0->dffml-model-autosklearn==0.0.1) (1.0.0)
2020-09-26T21:09:02.7581483Z Requirement already satisfied, skipping upgrade: psutil>=5.0 in /usr/share/miniconda/lib/python3.7/site-packages (from distributed->auto-sklearn>=0.7.0->dffml-model-autosklearn==0.0.1) (5.7.2)
2020-09-26T21:09:02.7700912Z Requirement already satisfied, skipping upgrade: cloudpickle>=1.5.0 in /usr/share/miniconda/lib/python3.7/site-packages (from distributed->auto-sklearn>=0.7.0->dffml-model-autosklearn==0.0.1) (1.6.0)
2020-09-26T21:09:02.7714469Z Requirement already satisfied, skipping upgrade: sortedcontainers!=2.0.0,!=2.0.1 in /usr/share/miniconda/lib/python3.7/site-packages (from distributed->auto-sklearn>=0.7.0->dffml-model-autosklearn==0.0.1) (2.2.2)
2020-09-26T21:09:02.7730047Z Requirement already satisfied, skipping upgrade: python-dateutil>=2.6.1 in /usr/share/miniconda/lib/python3.7/site-packages (from pandas<1.0->auto-sklearn>=0.7.0->dffml-model-autosklearn==0.0.1) (2.8.1)
2020-09-26T21:09:02.7759777Z Requirement already satisfied, skipping upgrade: pytz>=2017.2 in /usr/share/miniconda/lib/python3.7/site-packages (from pandas<1.0->auto-sklearn>=0.7.0->dffml-model-autosklearn==0.0.1) (2020.1)
2020-09-26T21:09:02.7781966Z Requirement already satisfied, skipping upgrade: pyparsing in /usr/share/miniconda/lib/python3.7/site-packages (from ConfigSpace<0.5,>=0.4.14->auto-sklearn>=0.7.0->dffml-model-autosklearn==0.0.1) (2.4.7)
2020-09-26T21:09:02.7795844Z Requirement already satisfied, skipping upgrade: cython in /usr/share/miniconda/lib/python3.7/site-packages (from ConfigSpace<0.5,>=0.4.14->auto-sklearn>=0.7.0->dffml-model-autosklearn==0.0.1) (0.29.21)
2020-09-26T21:09:02.7810269Z Requirement already satisfied, skipping upgrade: docutils>=0.3 in /usr/share/miniconda/lib/python3.7/site-packages (from pynisher>=0.4.2->auto-sklearn>=0.7.0->dffml-model-autosklearn==0.0.1) (0.16)
2020-09-26T21:09:02.7827008Z Requirement already satisfied, skipping upgrade: lazy-import in /usr/share/miniconda/lib/python3.7/site-packages (from smac<0.14,>=0.13->auto-sklearn>=0.7.0->dffml-model-autosklearn==0.0.1) (0.2.2)
2020-09-26T21:09:02.7867547Z Requirement already satisfied, skipping upgrade: heapdict in /usr/share/miniconda/lib/python3.7/site-packages (from zict>=0.1.3->distributed->auto-sklearn>=0.7.0->dffml-model-autosklearn==0.0.1) (1.0.1)
2020-09-26T21:09:02.7877678Z Requirement already satisfied, skipping upgrade: six>=1.5 in /usr/share/miniconda/lib/python3.7/site-packages (from python-dateutil>=2.6.1->pandas<1.0->auto-sklearn>=0.7.0->dffml-model-autosklearn==0.0.1) (1.15.0)
2020-09-26T21:09:02.7890856Z Building wheels for collected packages: auto-sklearn
2020-09-26T21:09:02.7898031Z   Building wheel for auto-sklearn (setup.py): started
2020-09-26T21:09:04.3633087Z   Building wheel for auto-sklearn (setup.py): finished with status 'done'
2020-09-26T21:09:04.3800153Z   Created wheel for auto-sklearn: filename=auto_sklearn-0.10.0-py3-none-any.whl size=4302076 sha256=fe614042bbcd8fb614dc71ce2e565e0720f64e4cc8f8dd8ed7b3ff5cc19d4aee
2020-09-26T21:09:04.3804465Z   Stored in directory: /home/runner/.cache/pip/wheels/ca/c3/5b/82cc60e025d647a85f3b74a9632b0efefdb8a29b5b4de53313
2020-09-26T21:09:04.3806871Z Successfully built auto-sklearn
2020-09-26T21:09:04.6045319Z Installing collected packages: auto-sklearn, dffml-model-autosklearn
2020-09-26T21:09:05.0770487Z   Running setup.py develop for dffml-model-autosklearn
2020-09-26T21:09:05.4333740Z Successfully installed auto-sklearn-0.10.0 dffml-model-autosklearn
2020-09-26T21:09:05.5685121Z + python3.7 setup.py test
2020-09-26T21:09:05.7973153Z WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
2020-09-26T21:09:05.7974481Z running test
2020-09-26T21:09:05.9050639Z running egg_info
2020-09-26T21:09:05.9088715Z writing dffml_model_autosklearn.egg-info/PKG-INFO
2020-09-26T21:09:05.9091590Z writing dependency_links to dffml_model_autosklearn.egg-info/dependency_links.txt
2020-09-26T21:09:05.9094264Z writing entry points to dffml_model_autosklearn.egg-info/entry_points.txt
2020-09-26T21:09:05.9096477Z writing requirements to dffml_model_autosklearn.egg-info/requires.txt
2020-09-26T21:09:05.9098256Z writing top-level names to dffml_model_autosklearn.egg-info/top_level.txt
2020-09-26T21:09:05.9111519Z reading manifest file 'dffml_model_autosklearn.egg-info/SOURCES.txt'
2020-09-26T21:09:05.9113489Z reading manifest template 'MANIFEST.in'
2020-09-26T21:09:05.9125604Z writing manifest file 'dffml_model_autosklearn.egg-info/SOURCES.txt'
2020-09-26T21:09:05.9616672Z running build_ext
2020-09-26T21:09:07.5340857Z /usr/share/miniconda/lib/python3.7/site-packages/pyparsing.py:3190: FutureWarning: Possible set intersection at position 3
2020-09-26T21:09:07.5342247Z   self.re = re.compile(self.reString)
2020-09-26T21:09:07.6113482Z test_run (tests.test_autoregressor_integration.TestAutoClassifierModel) ... ERROR
2020-09-26T21:09:07.6229332Z test_run (tests.test_autoclassifier_integration.TestAutoClassifierModel) ... --2020-09-26 21:09:07--  http://download.tensorflow.org/data/iris_training.csv
2020-09-26T21:09:07.6551911Z Resolving download.tensorflow.org (download.tensorflow.org)... 172.217.164.144, 2607:f8b0:4004:811::2010
2020-09-26T21:09:07.6567521Z Connecting to download.tensorflow.org (download.tensorflow.org)|172.217.164.144|:80... connected.
2020-09-26T21:09:07.8088504Z HTTP request sent, awaiting response... 200 OK
2020-09-26T21:09:07.8089703Z Length: 2194 (2.1K) [text/csv]
2020-09-26T21:09:07.8091628Z Saving to: ‘iris_training.csv’
2020-09-26T21:09:07.8092505Z 
2020-09-26T21:09:07.8093202Z      0K ..                                                    100% 1.77M=0.001s
2020-09-26T21:09:07.8093760Z 
2020-09-26T21:09:07.8094996Z 2020-09-26 21:09:07 (1.77 MB/s) - ‘iris_training.csv’ saved [2194/2194]
2020-09-26T21:09:07.8095759Z 
2020-09-26T21:09:07.8226963Z --2020-09-26 21:09:07--  http://download.tensorflow.org/data/iris_test.csv
2020-09-26T21:09:07.8235588Z Resolving download.tensorflow.org (download.tensorflow.org)... 172.217.164.144, 2607:f8b0:4004:811::2010
2020-09-26T21:09:07.8250317Z Connecting to download.tensorflow.org (download.tensorflow.org)|172.217.164.144|:80... connected.
2020-09-26T21:09:07.9502504Z HTTP request sent, awaiting response... 200 OK
2020-09-26T21:09:07.9503086Z Length: 573 [text/csv]
2020-09-26T21:09:07.9505720Z Saving to: ‘iris_test.csv’
2020-09-26T21:09:07.9507621Z 
2020-09-26T21:09:07.9509813Z      0K                                                       100% 2.62M=0s
2020-09-26T21:09:07.9510687Z 
2020-09-26T21:09:07.9511787Z 2020-09-26 21:09:07 (2.62 MB/s) - ‘iris_test.csv’ saved [573/573]
2020-09-26T21:09:07.9512096Z 
2020-09-26T21:09:08.0828993Z ERROR
2020-09-26T21:09:08.0830206Z 
2020-09-26T21:09:08.0831086Z ======================================================================
2020-09-26T21:09:08.0833001Z ERROR: test_run (tests.test_autoregressor_integration.TestAutoClassifierModel)
2020-09-26T21:09:08.0835744Z ----------------------------------------------------------------------
2020-09-26T21:09:08.0836857Z Traceback (most recent call last):
2020-09-26T21:09:08.0839691Z   File "/home/runner/work/dffml/dffml/dffml/util/asynctestcase.py", line 69, in run_it
2020-09-26T21:09:08.0841621Z     result = self.loop.run_until_complete(coro(*args, **kwargs))
2020-09-26T21:09:08.0843481Z   File "/usr/share/miniconda/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
2020-09-26T21:09:08.0844979Z     return future.result()
2020-09-26T21:09:08.0846387Z   File "/home/runner/work/dffml/dffml/model/autosklearn/tests/test_autoregressor_integration.py", line 80, in test_run
2020-09-26T21:09:08.0847350Z     await CLI.cli(*train_cmnd[1:])
2020-09-26T21:09:08.0848119Z   File "/home/runner/work/dffml/dffml/dffml/util/cli/cmd.py", line 224, in cli
2020-09-26T21:09:08.0849768Z     return await cmd.do_run()
2020-09-26T21:09:08.0850786Z   File "/home/runner/work/dffml/dffml/dffml/util/cli/cmd.py", line 203, in do_run
2020-09-26T21:09:08.0851485Z     return await self.run()
2020-09-26T21:09:08.0852150Z   File "/home/runner/work/dffml/dffml/dffml/cli/ml.py", line 40, in run
2020-09-26T21:09:08.0852915Z     return await train(self.model, self.sources)
2020-09-26T21:09:08.0853723Z   File "/home/runner/work/dffml/dffml/dffml/high_level.py", line 380, in train
2020-09-26T21:09:08.0854415Z     return await mctx.train(sctx)
2020-09-26T21:09:08.0855296Z   File "/home/runner/work/dffml/dffml/model/autosklearn/dffml_model_autosklearn/config.py", line 148, in train
2020-09-26T21:09:08.0856161Z     self.model.fit(x_train, y_train)
2020-09-26T21:09:08.0857120Z   File "/home/runner/work/dffml/dffml/model/autosklearn/dffml_model_autosklearn/autoregressor.py", line 25, in model
2020-09-26T21:09:08.0858567Z     self._model = autosklearn.regression.AutoSklearnRegressor(**config)
2020-09-26T21:09:08.0860167Z TypeError: __init__() got an unexpected keyword argument 'shared_mode'
2020-09-26T21:09:08.0860723Z 
2020-09-26T21:09:08.0861109Z ======================================================================
2020-09-26T21:09:08.0862070Z ERROR: test_run (tests.test_autoclassifier_integration.TestAutoClassifierModel)
2020-09-26T21:09:08.0863249Z ----------------------------------------------------------------------
2020-09-26T21:09:08.0863756Z Traceback (most recent call last):
2020-09-26T21:09:08.0864983Z   File "/home/runner/work/dffml/dffml/dffml/util/asynctestcase.py", line 69, in run_it
2020-09-26T21:09:08.0865867Z     result = self.loop.run_until_complete(coro(*args, **kwargs))
2020-09-26T21:09:08.0866810Z   File "/usr/share/miniconda/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
2020-09-26T21:09:08.0867594Z     return future.result()
2020-09-26T21:09:08.0868520Z   File "/home/runner/work/dffml/dffml/model/autosklearn/tests/test_autoclassifier_integration.py", line 80, in test_run
2020-09-26T21:09:08.0869417Z     await CLI.cli(*train_cmnd[1:])
2020-09-26T21:09:08.0870110Z   File "/home/runner/work/dffml/dffml/dffml/util/cli/cmd.py", line 224, in cli
2020-09-26T21:09:08.0870760Z     return await cmd.do_run()
2020-09-26T21:09:08.0871463Z   File "/home/runner/work/dffml/dffml/dffml/util/cli/cmd.py", line 203, in do_run
2020-09-26T21:09:08.0872286Z     return await self.run()
2020-09-26T21:09:08.0872960Z   File "/home/runner/work/dffml/dffml/dffml/cli/ml.py", line 40, in run
2020-09-26T21:09:08.0873702Z     return await train(self.model, self.sources)
2020-09-26T21:09:08.0874493Z   File "/home/runner/work/dffml/dffml/dffml/high_level.py", line 380, in train
2020-09-26T21:09:08.0875184Z     return await mctx.train(sctx)
2020-09-26T21:09:08.0876056Z   File "/home/runner/work/dffml/dffml/model/autosklearn/dffml_model_autosklearn/config.py", line 148, in train
2020-09-26T21:09:08.0876920Z     self.model.fit(x_train, y_train)
2020-09-26T21:09:08.0877882Z   File "/home/runner/work/dffml/dffml/model/autosklearn/dffml_model_autosklearn/autoclassifier.py", line 26, in model
2020-09-26T21:09:08.0878721Z     **config
2020-09-26T21:09:08.0881259Z TypeError: __init__() got an unexpected keyword argument 'shared_mode'
2020-09-26T21:09:08.0881684Z 
2020-09-26T21:09:08.0882144Z ----------------------------------------------------------------------
2020-09-26T21:09:08.0882462Z Ran 2 tests in 0.549s
2020-09-26T21:09:08.0882693Z 
2020-09-26T21:09:08.0882989Z FAILED (errors=2)
2020-09-26T21:09:08.0883695Z Test failed: <unittest.runner.TextTestResult run=2 errors=2 failures=0>
2020-09-26T21:09:08.1005402Z error: Test failed: <unittest.runner.TextTestResult run=2 errors=2 failures=0>
```

From CI run: https://github.com/pdxjohnny/dffml/runs/1170954826

**Comment by sk-ip** [comment]
@pdxjohnny , this line needs to be removed, that should fix this issue

https://github.com/intel/dffml/blob/4d0ca9f32f015bd429e74cf9e1788d3bd0cf25f1/model/autosklearn/dffml_model_autosklearn/config.py#L83

**Comment by sk-ip** [comment]
My master branch is a mess right now hence cannot push the changes :|

**Comment by pdxjohnny** [comment]
@sk-ip Awesome, thanks!
