### ISSUE TITLE
question: How was going through the official documentation of DFFML and found that it does not support any OS other than LINUX, i'm a mac user. So, is there anyway I can use the software for personal usage as well as development? 

### ISSUE THREAD

**Issue by anushka17agarwal** [intel/dffml#885]

**Comment by pdxjohnny** [comment]
Hi @anushka17agarwal, you should be able to use the software on MacOS, it's just not guaranteed to work at the moment. Please let us know how it goes and what issues you run into so that we can tack them. That way we will know what issues we need to resolve to be able to officially support it.

**Comment by pdxjohnny** [comment]
I'm looking into enabling the CI for MacOS: https://github.com/pdxjohnny/dffml/runs/1365842990

We have two issues around the cached download tests, but everything else is looking okay unit test wise.

```
======================================================================
ERROR: test_cached_download (tests.util.test_net.TestNet)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/urllib/request.py", line 1350, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/http/client.py", line 1277, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/http/client.py", line 1323, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/http/client.py", line 1272, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/http/client.py", line 1032, in _send_output
    self.send(msg)
  File "/Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/http/client.py", line 972, in send
    self.connect()
  File "/Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/http/client.py", line 944, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/runner/work/dffml/dffml/dffml/util/asynctestcase.py", line 69, in run_it
    result = self.loop.run_until_complete(coro(*args, **kwargs))
  File "/Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/Users/runner/work/dffml/dffml/.eggs/httptest-0.0.15-py3.7.egg/httptest/httptest.py", line 304, in wrap
    res = await func(*args, ts=self, **kwargs)
  File "/Users/runner/work/dffml/dffml/tests/util/test_net.py", line 81, in test_cached_download
    shutil.unpack_archive(await func(), extracted)
  File "/Users/runner/work/dffml/dffml/dffml/util/net.py", line 130, in wrapper
    url, protocol_allowlist=protocol_allowlist
  File "/Users/runner/work/dffml/dffml/dffml/util/net.py", line 57, in sync_urlopen
    return urllib.request.urlopen(url)
  File "/Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/urllib/request.py", line 1378, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/urllib/request.py", line 1352, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>

======================================================================
ERROR: test_cached_download_unpack_archive (tests.util.test_net.TestNet)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/urllib/request.py", line 1350, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/http/client.py", line 1277, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/http/client.py", line 1323, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/http/client.py", line 1272, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/http/client.py", line 1032, in _send_output
    self.send(msg)
  File "/Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/http/client.py", line 972, in send
    self.connect()
  File "/Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/http/client.py", line 944, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/runner/work/dffml/dffml/dffml/util/asynctestcase.py", line 69, in run_it
    result = self.loop.run_until_complete(coro(*args, **kwargs))
  File "/Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/Users/runner/work/dffml/dffml/.eggs/httptest-0.0.15-py3.7.egg/httptest/httptest.py", line 304, in wrap
    res = await func(*args, ts=self, **kwargs)
  File "/Users/runner/work/dffml/dffml/tests/util/test_net.py", line 101, in test_cached_download_unpack_archive
    self.verify_extracted_contents(await func())
  File "/Users/runner/work/dffml/dffml/dffml/util/net.py", line 214, in wrapper
    await extract()
  File "/Users/runner/work/dffml/dffml/dffml/util/net.py", line 130, in wrapper
    url, protocol_allowlist=protocol_allowlist
  File "/Users/runner/work/dffml/dffml/dffml/util/net.py", line 57, in sync_urlopen
    return urllib.request.urlopen(url)
  File "/Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/urllib/request.py", line 1378, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/urllib/request.py", line 1352, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>

----------------------------------------------------------------------
```
