### ISSUE TITLE
plugins: models: Track support for Windows and add to CI

### ISSUE THREAD

**Issue by yashlamba** [intel/dffml#892]
- [ ] scratch
- [ ] scikit
- [ ] tensorflow
- [ ] tensorflow_hub
- [ ] transformers
- [ ] vowpalWabbit
- [x] ~autosklearn~ (Not supported on Windows)
- [ ] xgboost
- [ ] pytorch
- [ ] spacy

**Comment by yashlamba** [comment]
**dffml-model-pytorch**
All the tests are failing for Pytorch, the issue maybe because of the recent PyTorch update.

Since Pytorch needs to be explicitly installed for dffml (only windows) right now (see #877), the following command was used:
`pip install torch===1.7.0 torchvision===0.8.1 -f https://download.pytorch.org/whl/torch_stable.html`

There is this weird test loop happening each time I ran PyTorch tests too.

```console
python setup.py test
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic te
st entry point independent of test runner are encouraged to use tox.
running egg_info
writing dffml_model_pytorch.egg-info\PKG-INFO
writing dependency_links to dffml_model_pytorch.egg-info\dependency_links.txt
writing entry points to dffml_model_pytorch.egg-info\entry_points.txt
writing requirements to dffml_model_pytorch.egg-info\requires.txt
writing top-level names to dffml_model_pytorch.egg-info\top_level.txt
reading manifest file 'dffml_model_pytorch.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'dffml_model_pytorch.egg-info\SOURCES.txt'
running build_ext
test_00_train (tests.test_pytorchnet.TestPyTorchNeuralNetwork) ... running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic te
st entry point independent of test runner are encouraged to use tox.
running egg_info
creating dffml_model_pytorch.egg-info
writing dffml_model_pytorch.egg-info\PKG-INFO
writing dependency_links to dffml_model_pytorch.egg-info\dependency_links.txt
writing entry points to dffml_model_pytorch.egg-info\entry_points.txt
writing requirements to dffml_model_pytorch.egg-info\requires.txt
writing top-level names to dffml_model_pytorch.egg-info\top_level.txt
writing manifest file 'dffml_model_pytorch.egg-info\SOURCES.txt'
reading manifest file 'dffml_model_pytorch.egg-info\SOURCES.txt'
writing manifest file 'dffml_model_pytorch.egg-info\SOURCES.txt'
running build_ext

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic te
st entry point independent of test runner are encouraged to use tox.
running egg_info
writing dffml_model_pytorch.egg-info\PKG-INFO
writing dependency_links to dffml_model_pytorch.egg-info\dependency_links.txt
writing entry points to dffml_model_pytorch.egg-info\entry_points.txt
writing requirements to dffml_model_pytorch.egg-info\requires.txt
writing top-level names to dffml_model_pytorch.egg-info\top_level.txt
reading manifest file 'dffml_model_pytorch.egg-info\SOURCES.txt'
writing manifest file 'dffml_model_pytorch.egg-info\SOURCES.txt'
running build_ext

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic te
st entry point independent of test runner are encouraged to use tox.
running egg_info
writing dffml_model_pytorch.egg-info\PKG-INFO
writing dependency_links to dffml_model_pytorch.egg-info\dependency_links.txt
writing entry points to dffml_model_pytorch.egg-info\entry_points.txt
writing requirements to dffml_model_pytorch.egg-info\requires.txt
writing top-level names to dffml_model_pytorch.egg-info\top_level.txt
reading manifest file 'dffml_model_pytorch.egg-info\SOURCES.txt'
writing manifest file 'dffml_model_pytorch.egg-info\SOURCES.txt'
running build_ext

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic te
st entry point independent of test runner are encouraged to use tox.
running egg_info
writing dffml_model_pytorch.egg-info\PKG-INFO
writing dependency_links to dffml_model_pytorch.egg-info\dependency_links.txt
writing entry points to dffml_model_pytorch.egg-info\entry_points.txt
writing requirements to dffml_model_pytorch.egg-info\requires.txt
writing top-level names to dffml_model_pytorch.egg-info\top_level.txt
reading manifest file 'dffml_model_pytorch.egg-info\SOURCES.txt'
writing manifest file 'dffml_model_pytorch.egg-info\SOURCES.txt'
running build_ext

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
ERROR
test_01_accuracy (tests.test_pytorchnet.TestPyTorchNeuralNetwork) ... ERROR
test_02_predict (tests.test_pytorchnet.TestPyTorchNeuralNetwork) ... ERROR
test_shell (tests.test_pytorchnet.TestPyTorchNeuralNetwork) ... running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic te
st entry point independent of test runner are encouraged to use tox.
running egg_info
creating dffml_model_pytorch.egg-info
writing dffml_model_pytorch.egg-info\PKG-INFO
writing dependency_links to dffml_model_pytorch.egg-info\dependency_links.txt
writing entry points to dffml_model_pytorch.egg-info\entry_points.txt
writing requirements to dffml_model_pytorch.egg-info\requires.txt
writing top-level names to dffml_model_pytorch.egg-info\top_level.txt
writing manifest file 'dffml_model_pytorch.egg-info\SOURCES.txt'
reading manifest file 'dffml_model_pytorch.egg-info\SOURCES.txt'
writing manifest file 'dffml_model_pytorch.egg-info\SOURCES.txt'
running build_ext

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic te
st entry point independent of test runner are encouraged to use tox.
running egg_info
writing dffml_model_pytorch.egg-info\PKG-INFO
writing dependency_links to dffml_model_pytorch.egg-info\dependency_links.txt
writing entry points to dffml_model_pytorch.egg-info\entry_points.txt
writing requirements to dffml_model_pytorch.egg-info\requires.txt
writing top-level names to dffml_model_pytorch.egg-info\top_level.txt
reading manifest file 'dffml_model_pytorch.egg-info\SOURCES.txt'
writing manifest file 'dffml_model_pytorch.egg-info\SOURCES.txt'
running build_ext

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic te
st entry point independent of test runner are encouraged to use tox.
running egg_info
writing dffml_model_pytorch.egg-info\PKG-INFO
writing dependency_links to dffml_model_pytorch.egg-info\dependency_links.txt
writing entry points to dffml_model_pytorch.egg-info\entry_points.txt
writing requirements to dffml_model_pytorch.egg-info\requires.txt
writing top-level names to dffml_model_pytorch.egg-info\top_level.txt
reading manifest file 'dffml_model_pytorch.egg-info\SOURCES.txt'
writing manifest file 'dffml_model_pytorch.egg-info\SOURCES.txt'
running build_ext

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic te
st entry point independent of test runner are encouraged to use tox.
running egg_info
writing dffml_model_pytorch.egg-info\PKG-INFO
writing dependency_links to dffml_model_pytorch.egg-info\dependency_links.txt
writing entry points to dffml_model_pytorch.egg-info\entry_points.txt
writing requirements to dffml_model_pytorch.egg-info\requires.txt
writing top-level names to dffml_model_pytorch.egg-info\top_level.txt
reading manifest file 'dffml_model_pytorch.egg-info\SOURCES.txt'
writing manifest file 'dffml_model_pytorch.egg-info\SOURCES.txt'
running build_ext

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
ERROR
test_shell (tests.test_resnet18.TestResNet18Model) ... ^Z/bin/bash: c:\users\yashl\main\projects\dffml\model\pytorch\te
sts\..\examples\resnet18\unknown_data.sh: No such file or directory
ERROR

======================================================================
ERROR: test_00_train (tests.test_pytorchnet.TestPyTorchNeuralNetwork)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\yashl\main\projects\dffml\dffml\util\asynctestcase.py", line 69, in run_it
    result = self.loop.run_until_complete(coro(*args, **kwargs))
  File "C:\Users\yashl\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_compl
ete
    return future.result()
  File "c:\users\yashl\main\projects\dffml\dffml\util\net.py", line 215, in wrapper
    return await func(*(list(args) + [directory_path]), **kwds)
  File "c:\users\yashl\main\projects\dffml\model\pytorch\tests\test_pytorchnet.py", line 91, in test_00_train
    await train(
  File "c:\users\yashl\main\projects\dffml\dffml\high_level.py", line 380, in train
    return await mctx.train(sctx)
  File "c:\users\yashl\main\projects\dffml\model\pytorch\dffml_model_pytorch\pytorch_base.py", line 271, in train
    loss = self.criterion(outputs, labels)
  File "C:\Users\yashl\Main\Projects\dffml\.venv\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\yashl\Main\Projects\dffml\.venv\lib\site-packages\torch\nn\modules\loss.py", line 947, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "C:\Users\yashl\Main\Projects\dffml\.venv\lib\site-packages\torch\nn\functional.py", line 2422, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "C:\Users\yashl\Main\Projects\dffml\.venv\lib\site-packages\torch\nn\functional.py", line 2218, in nll_loss
    ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: Expected object of scalar type Long but got scalar type Int for argument #2 'target' in call to _thnn_nll
_loss_forward

======================================================================
ERROR: test_01_accuracy (tests.test_pytorchnet.TestPyTorchNeuralNetwork)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\yashl\main\projects\dffml\dffml\util\asynctestcase.py", line 69, in run_it
    result = self.loop.run_until_complete(coro(*args, **kwargs))
  File "C:\Users\yashl\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_compl
ete
    return future.result()
  File "c:\users\yashl\main\projects\dffml\dffml\util\net.py", line 215, in wrapper
    return await func(*(list(args) + [directory_path]), **kwds)
  File "c:\users\yashl\main\projects\dffml\model\pytorch\tests\test_pytorchnet.py", line 107, in test_01_accuracy
    acc = await accuracy(
  File "c:\users\yashl\main\projects\dffml\dffml\high_level.py", line 439, in accuracy
    return float(await mctx.accuracy(sctx))
  File "c:\users\yashl\main\projects\dffml\model\pytorch\dffml_model_pytorch\pytorch_base.py", line 335, in accuracy
    raise ModelNotTrained("Train model before assessing for accuracy.")
dffml.model.model.ModelNotTrained: Train model before assessing for accuracy.

======================================================================
ERROR: test_02_predict (tests.test_pytorchnet.TestPyTorchNeuralNetwork)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\yashl\main\projects\dffml\dffml\util\asynctestcase.py", line 69, in run_it
    result = self.loop.run_until_complete(coro(*args, **kwargs))
  File "C:\Users\yashl\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_compl
ete
    return future.result()
  File "c:\users\yashl\main\projects\dffml\dffml\util\net.py", line 215, in wrapper
    return await func(*(list(args) + [directory_path]), **kwds)
  File "c:\users\yashl\main\projects\dffml\model\pytorch\tests\test_pytorchnet.py", line 126, in test_02_predict
    async for key, features, prediction in predict(
  File "c:\users\yashl\main\projects\dffml\dffml\high_level.py", line 504, in predict
    async for record in mctx.predict(sctx):
  File "c:\users\yashl\main\projects\dffml\model\pytorch\dffml_model_pytorch\pytorch_base.py", line 385, in predict
    raise ModelNotTrained("Train model before prediction.")
dffml.model.model.ModelNotTrained: Train model before prediction.

======================================================================
ERROR: test_shell (tests.test_pytorchnet.TestPyTorchNeuralNetwork)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\yashl\main\projects\dffml\dffml\util\asynctestcase.py", line 69, in run_it
    result = self.loop.run_until_complete(coro(*args, **kwargs))
  File "C:\Users\yashl\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_compl
ete
    return future.result()
  File "c:\users\yashl\main\projects\dffml\dffml\util\net.py", line 215, in wrapper
    return await func(*(list(args) + [directory_path]), **kwds)
  File "c:\users\yashl\main\projects\dffml\dffml\util\net.py", line 215, in wrapper
    return await func(*(list(args) + [directory_path]), **kwds)
  File "c:\users\yashl\main\projects\dffml\dffml\util\net.py", line 215, in wrapper
    return await func(*(list(args) + [directory_path]), **kwds)
  File "c:\users\yashl\main\projects\dffml\model\pytorch\tests\test_pytorchnet.py", line 176, in test_shell
    await CLI.cli(*train_command[1:])
  File "c:\users\yashl\main\projects\dffml\dffml\util\cli\cmd.py", line 224, in cli
    return await cmd.do_run()
  File "c:\users\yashl\main\projects\dffml\dffml\util\cli\cmd.py", line 203, in do_run
    return await self.run()
  File "c:\users\yashl\main\projects\dffml\dffml\cli\ml.py", line 40, in run
    return await train(self.model, self.sources)
  File "c:\users\yashl\main\projects\dffml\dffml\high_level.py", line 380, in train
    return await mctx.train(sctx)
  File "c:\users\yashl\main\projects\dffml\model\pytorch\dffml_model_pytorch\pytorch_base.py", line 271, in train
    loss = self.criterion(outputs, labels)
  File "C:\Users\yashl\Main\Projects\dffml\.venv\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\yashl\Main\Projects\dffml\.venv\lib\site-packages\torch\nn\modules\loss.py", line 947, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "C:\Users\yashl\Main\Projects\dffml\.venv\lib\site-packages\torch\nn\functional.py", line 2422, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "C:\Users\yashl\Main\Projects\dffml\.venv\lib\site-packages\torch\nn\functional.py", line 2218, in nll_loss
    ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: Expected object of scalar type Long but got scalar type Int for argument #2 'target' in call to _thnn_nll
_loss_forward

======================================================================
ERROR: test_shell (tests.test_resnet18.TestResNet18Model)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\yashl\main\projects\dffml\dffml\util\asynctestcase.py", line 69, in run_it
    result = self.loop.run_until_complete(coro(*args, **kwargs))
  File "C:\Users\yashl\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_compl
ete
    return future.result()
  File "c:\users\yashl\main\projects\dffml\dffml\util\net.py", line 215, in wrapper
    return await func(*(list(args) + [directory_path]), **kwds)
  File "c:\users\yashl\main\projects\dffml\model\pytorch\tests\test_resnet18.py", line 40, in test_shell
    subprocess.check_output(
  File "C:\Users\yashl\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\yashl\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bash', 'c:\\users\\yashl\\main\\projects\\dffml\\model\\pytorch\\tests\\..\\e
xamples\\resnet18\\unknown_data.sh']' returned non-zero exit status 127.

----------------------------------------------------------------------
Ran 5 tests in 290.327s

FAILED (errors=5)
Test failed: <unittest.runner.TextTestResult run=5 errors=5 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=5 errors=5 failures=0>
```

**Comment by yashlamba** [comment]
**dffml-model-spacy**
All tests are fine except one and that might just be because I wasn't using a bash terminal. Putting this here just for the record and note for CI:

```console
======================================================================
ERROR: test_run (tests.test_ner_integration.TestSpacyNERModel)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\yashl\main\projects\dffml\dffml\util\asynctestcase.py", line 69, in run_it
    result = self.loop.run_until_complete(coro(*args, **kwargs))
  File "C:\Users\yashl\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_compl
ete
    return future.result()
  File "c:\users\yashl\main\projects\dffml\model\spacy\tests\test_ner_integration.py", line 212, in test_run
    with directory_with_csv_files() as tempdir:
  File "C:\Users\yashl\AppData\Local\Programs\Python\Python38\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "c:\users\yashl\main\projects\dffml\model\spacy\tests\test_ner_integration.py", line 25, in directory_with_csv_f
iles
    subprocess.check_output(
  File "C:\Users\yashl\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\yashl\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bash', 'c:\\users\\yashl\\main\\projects\\dffml\\model\\spacy\\examples\\ner\
\train_data.sh']' returned non-zero exit status 127.

----------------------------------------------------------------------
Ran 5 tests in 31.055s

FAILED (errors=1)
Test failed: <unittest.runner.TextTestResult run=5 errors=1 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=5 errors=1 failures=0>
```
