### ISSUE TITLE
model: transformers: AttributeError: 'OneDeviceStrategy' object has no attribute 'experimental_run_v2'

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#953]
This happened after upgrading to tensorflow version 2.4.0

```
======================================================================
ERROR: test_run (tests.test_classification_integration.TestHFClassifier)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/dffml/dffml/dffml/util/asynctestcase.py", line 69, in run_it
    result = self.loop.run_until_complete(coro(*args, **kwargs))
  File "/usr/share/miniconda/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/home/runner/work/dffml/dffml/model/transformers/tests/test_classification_integration.py", line 114, in test_run
    data_filename,
  File "/home/runner/work/dffml/dffml/dffml/util/cli/cmd.py", line 224, in cli
    return await cmd.do_run()
  File "/home/runner/work/dffml/dffml/dffml/util/cli/cmd.py", line 203, in do_run
    return await self.run()
  File "/home/runner/work/dffml/dffml/dffml/cli/ml.py", line 40, in run
    return await train(self.model, self.sources)
  File "/home/runner/work/dffml/dffml/dffml/high_level.py", line 388, in train
    return await mctx.train(sctx)
  File "/home/runner/work/dffml/dffml/model/transformers/dffml_model_transformers/classification/classification_model.py", line 328, in train
    trainer.train()
  File "/usr/share/miniconda/lib/python3.7/site-packages/transformers/trainer_tf.py", line 412, in train
    for step, training_loss in enumerate(self._training_steps(train_ds, optimizer)):
  File "/usr/share/miniconda/lib/python3.7/site-packages/transformers/trainer_tf.py", line 459, in _training_steps
    for i, loss in enumerate(self._accumulate_next_gradients(ds)):
  File "/usr/share/miniconda/lib/python3.7/site-packages/transformers/trainer_tf.py", line 492, in _accumulate_next_gradients
    yield _accumulate_next()
  File "/usr/share/miniconda/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "/usr/share/miniconda/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 871, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/usr/share/miniconda/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 726, in _initialize
    *args, **kwds))
  File "/usr/share/miniconda/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2969, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/usr/share/miniconda/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3361, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/usr/share/miniconda/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3206, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/usr/share/miniconda/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 990, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/share/miniconda/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 634, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/usr/share/miniconda/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 977, in wrapper
    raise e.ag_error_metadata.to_exception(e)
AttributeError: in user code:

    /usr/share/miniconda/lib/python3.7/site-packages/transformers/trainer_tf.py:488 _accumulate_next  *
        return self._accumulate_gradients(per_replica_features, per_replica_labels)
    /usr/share/miniconda/lib/python3.7/site-packages/transformers/trainer_tf.py:498 _accumulate_gradients  *
        per_replica_loss = self.args.strategy.experimental_run_v2(

    AttributeError: 'OneDeviceStrategy' object has no attribute 'experimental_run_v2'


======================================================================
ERROR: test_00_train (tests.test_ner_model.TestNERModel)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/dffml/dffml/dffml/util/asynctestcase.py", line 69, in run_it
    result = self.loop.run_until_complete(coro(*args, **kwargs))
  File "/usr/share/miniconda/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/home/runner/work/dffml/dffml/model/transformers/tests/test_ner_model.py", line 75, in test_00_train
    await mctx.train(sctx)
  File "/home/runner/work/dffml/dffml/model/transformers/dffml_model_transformers/ner/ner_model.py", line 389, in train
    trainer.train()
  File "/usr/share/miniconda/lib/python3.7/site-packages/transformers/trainer_tf.py", line 412, in train
    for step, training_loss in enumerate(self._training_steps(train_ds, optimizer)):
  File "/usr/share/miniconda/lib/python3.7/site-packages/transformers/trainer_tf.py", line 459, in _training_steps
    for i, loss in enumerate(self._accumulate_next_gradients(ds)):
  File "/usr/share/miniconda/lib/python3.7/site-packages/transformers/trainer_tf.py", line 492, in _accumulate_next_gradients
    yield _accumulate_next()
  File "/usr/share/miniconda/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "/usr/share/miniconda/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 871, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/usr/share/miniconda/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 726, in _initialize
    *args, **kwds))
  File "/usr/share/miniconda/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2969, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/usr/share/miniconda/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3361, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/usr/share/miniconda/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3206, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/usr/share/miniconda/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 990, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/share/miniconda/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 634, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/usr/share/miniconda/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 977, in wrapper
    raise e.ag_error_metadata.to_exception(e)
AttributeError: in user code:

    /usr/share/miniconda/lib/python3.7/site-packages/transformers/trainer_tf.py:488 _accumulate_next  *
        return self._accumulate_gradients(per_replica_features, per_replica_labels)
    /usr/share/miniconda/lib/python3.7/site-packages/transformers/trainer_tf.py:498 _accumulate_gradients  *
        per_replica_loss = self.args.strategy.experimental_run_v2(

    AttributeError: 'OneDeviceStrategy' object has no attribute 'experimental_run_v2'
```

**Comment by pdxjohnny** [comment]
Duplicate of #844

Caused by updating tensorflow to 2.4.0 but keeping transformers <3.1.0
